<%
/************************************************************************************
Generated by AIDesigner 5.6.0.5
************************************************************************************
보고서 제목 : 회원매출상세내역현황
작성일 : 2017년4월21일 9시28분42초
수정일 : 2017년6월27일 18시5분37초
작성자 :
************************************************************************************/
%>

<%@ page pageEncoding="UTF-8" %>
<%@ page contentType="text/html; charset=utf-8" %>

<%@ page import="java.sql.*,java.io.*,java.lang.*,java.text.*,java.util.*,java.net.URL" %>
<%@ page import="com.activeintra.manager.*" %>
<%@ page import="com.activeintra.url.*" %>
<%@ page import="com.activeintra.util.uds.*" %>
<%@ page import="org.apache.log4j.Logger" %>
<%@ page import="org.apache.log4j.PropertyConfigurator" %>


<%
Object[] userObj = null;
HttpParameterDecoder decoder = HttpParameterDecoder.newInstance(request, application);
request.setAttribute("paramsDecoder", decoder);

String reportMode = decoder.getParameter("reportMode");
String reportParams = decoder.getParameter("reportParams");
if(reportMode!=null){
	if(reportMode.equals("PDF")){
		if(reportParams == null || reportParams.toLowerCase().indexOf("pdfserversave:true") == -1){
			out.clear();
			out=pageContext.pushBody();
		}
	}
	else if(reportMode.equals("EXCEL")){
		if(reportParams == null || reportParams.toLowerCase().indexOf("excelserversave:true") == -1){
			out.clear();
			out=pageContext.pushBody();
		}
	}
	else if(reportMode.equals("AR5")){
		out.clear();
		out=pageContext.pushBody();
	}
}

ReportHandler handler = new ReportHandler(pageContext, request, response, userObj, decoder);
handler.service(out);
handler = null;
%>

<%!
private volatile ReportInitializer initializer;
//보고서 초기화 - 한번만 실행되고 사용자 Request에서 반복사용가능한 코드를 기술
public void jspInit() {
	initializer = new ReportInitializer(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
	//수정되지 않는 정적 Query변수들을 초기화
	//sql_param
	StringBuilder sql_param = new StringBuilder();
	sql_param.setLength(0);
	sql_param.append("SELECT 	TO_CHAR(SYSDATE,'YYYY-MM-DD') AS T ");
	sql_param.append(",	'점포 : '||NVl(FN_GET_STR_NAME('^P_STR_CODE^','^P_CORP_CODE^'),'전체') AS STR_NAME ");
	sql_param.append(",             SUBSTR('^P_SALE_DT^',0,4)||'년 '||	SUBSTR('^P_SALE_DT^',5,2)||'월 '||	SUBSTR('^P_SALE_DT^',7,2)||'일' AS SALE_DT ");
	sql_param.append(" ");
	sql_param.append("FROM	DUAL ");
	initializer.prepareQuery("sql_param", sql_param.toString());

	//sql_pay
	StringBuilder sql_pay = new StringBuilder();
	sql_pay.setLength(0);
	sql_pay.append("        SELECT SP.CORP_CODE ");
	sql_pay.append("        , SP.CUST_NO ");
	sql_pay.append("        , SP.POS_NO ");
	sql_pay.append("        , CC.CUST_NAME ");
	sql_pay.append("        , CC.ACCT_DEPT ");
	sql_pay.append("        , FN_GET_STR_NAME(SP.STR_CODE,SP.CORP_CODE) AS STR_NAME ");
	sql_pay.append("        , SP.PAY_AMT ");
	sql_pay.append("        , SP.SALE_DT ");
	sql_pay.append("        , SP.STR_CODE ");
	sql_pay.append("        , SP.TRXN_NO ");
	sql_pay.append("        , SP.ZAN_AMT ");
	sql_pay.append("        , SP.PAY_AMT - SP.ZAN_AMT AS PAY_ZAN_AMT ");
	sql_pay.append("        , DECODE(SP.CANC_FLAG,'2','반품','정상') AS CANC_FLAG ");
	sql_pay.append("        ,SUBSTR(SP.SALE_DT,0,4)||'-'|| ");
	sql_pay.append("         SUBSTR(SP.SALE_DT,5,2)||'-'|| ");
	sql_pay.append("         SUBSTR(SP.SALE_DT,7,2) AS SALE_DT_ ");
	sql_pay.append("        FROM SL_SALE_PAYMENT SP ");
	sql_pay.append("        ,    CS_CUST        CC ");
	sql_pay.append("        WHERE SP.CANC_FLAG IN ('2','0') ");
	sql_pay.append("        AND   SP.GRE_TYPE IN ('00','35') ");
	sql_pay.append("        AND   SP.PAY_METH ='04' ");
	sql_pay.append("        AND   SP.CORP_CODE     =   CC.CORP_CODE ");
	sql_pay.append("        AND   SP.CUST_NO       =   CC.CUST_NO ");
	sql_pay.append("        AND     SP.CORP_CODE   =   '^P_CORP_CODE^' ");
	sql_pay.append("        AND     SP.STR_CODE    =   '^P_STR_CODE^' ");
	sql_pay.append("        AND     SP.SALE_DT     =   '^P_SALE_DT^' ");
	sql_pay.append("        ORDER BY POS_NO,TRXN_NO,CUST_NO ");
	initializer.prepareQuery("sql_pay", sql_pay.toString());
}

class ReportHandler{
	//공통 변수 선언
	private final Logger logger = Logger.getLogger("com.activeintra");
	private Object[] userObj = null;
	private int nStartPage;		//각 쉬트별 시작 페이지 저장
	private int nMaxPage;		//한 쉬트가 실행된 후 생성된 최대 페이지 번호 저장
	private int nPageNum;		//현재 페이지 번호
	private int nYStartPos;		//쉬트에서 Y 시작 좌표
	private int nYEndPos;		//쉬트에서 Y 끝 좌표
	private int nYCurPos;		//현재 Y 좌표
	private int nYSavePos;		//연결된 멀티 프레임 쉬트에서 시작 Y 좌표 저장
	private int nYLastPos;		//연결된 멀티 프레임 쉬트에서 각 프레임의 마지막 Y 좌표 저장
	private int nXStartPos;		//쉬트에서 X 시작 좌표
	private int nXEndPos;		//쉬트에서 X 끝 좌표
	private int nXCurPos;		//현재 X 좌표
	private int nXSavePos;		//연결된 멀티 프레임 쉬트에서 시작 X 좌표 저장
	private int  nXLastPos;		//연결된 멀티 프레임 쉬트에서 각 프레임의 마지막 X 좌표 저장
	private boolean bIsBeforePageSkip;		//조건 밴드에서 페이지 넘기기 여부 판단
	private int nLoopRef;		//절대 양식에서 루프 참조 변수
	private int CELL_OBJECT = 0;
	private int DRAW_OBJECT = 1;
	private String isEmpty="";		//빈 문자열 비교에 사용
	private Map<String, String> mapParam;

	private int nBandRepeatType;	//1이면 반복밴드 가로 반복
	private int nBandWidth;		//반복밴드의 가로 폭
	private int nBandOffset;		//반복밴드 가로 반복 offset값
	private int nYBandStart;		//반복밴드 가로 반복 Y 시작 좌표
	private int nYBandEnd;		//반복밴드 가로 반복 Y 끝 좌표
	private int nHorRepeatNum;		//반복밴드 가로 반복 횟수
	private int nHorRepeatCnt;		//반복밴드 가로 반복 횟수 카운팅
	private Map<String, Integer> mapLeft;		//셀 Left
	private Map<String, Integer> mapTop;		//셀 Top
	private Map<String, Integer> mapWidth;		//셀 Width
	private Map<String, Integer> mapHeight;		//셀 Height
	private Map<String, String> mapStyle;		//셀 Style
	private HttpServletRequest request;
	private HttpServletResponse response;
	private PageContext pageContext;
	private JspWriter out;
	private HttpParameterDecoder decoder;

	private AIScriptManager manager;
	private String reportMode="AIScript";
	private String pdfFilename="";
	private String excelFilename="";

	//-----데이터 변수 선언-----
	String AI_STRING_OBJ2 = "";
	String AI_STRING_OBJ3 = "";
	String sheet10_A1 = "";
	String sheet10_A2 = "";
	String sheet10_D2 = "";
	String sheet20_A2 = "";
	String sheet20_B2 = "";
	String sheet20_C2 = "";
	String sheet20_D2 = "";
	String sheet20_E2 = "";
	String sheet20_F2 = "";
	String sheet20_G2 = "";
	String sheet20_H2 = "";
	String sheet20_A3_Buf;
	int sheet20_A3_YPos;
	boolean sheet20_A3_Flag;
	String sheet20_A3 = "";
	String sheet20_B3_Buf;
	int sheet20_B3_YPos;
	boolean sheet20_B3_Flag;
	String sheet20_B3 = "";
	String sheet20_C3_Buf;
	int sheet20_C3_YPos;
	boolean sheet20_C3_Flag;
	String sheet20_C3 = "";
	String sheet20_D3 = "";
	String sheet20_E3 = "";
	String sheet20_F3 = "";
	String sheet20_G3 = "";
	long sheet20_H3 = 0L;
	boolean bEnabledVirtualMerge_sh1_f1;
	String sheet20_A4 = "";
	long sheet20_H4 = 0L;
	String sheet20_A5 = "";
	long sheet20_H5 = 0L;

	//-----Connection, Statement, ResultSet 객체 선언-----
	private Connection conn_retail; 	 //retail Connection 객체
	private java.sql.PreparedStatement stat_param;		//ResultSet param 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet param;		//ResultSet param 객체
	private java.sql.PreparedStatement stat_pay;		//ResultSet pay 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet pay;		//ResultSet pay 객체

	//-----SQL 변수 선언-----
	private StringBuilder sql_param = new StringBuilder();		//ResultSet param 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_pay = new StringBuilder();		//ResultSet pay 객체를 생성하기 위한 쿼리문 저장

	//-----쿼리 필드 변수 선언-----
	//ResultSet param 객체에서 필드 값을 받는 쿼리 필드 변수
	private String param_T;
	private String param_STR_NAME;
	private String param_SALE_DT;

	//ResultSet pay 객체에서 필드 값을 받는 쿼리 필드 변수
	private String pay_CORP_CODE;
	private String pay_CUST_NO;
	private String pay_POS_NO;
	private String pay_CUST_NAME;
	private String pay_ACCT_DEPT;
	private String pay_STR_NAME;
	private long pay_PAY_AMT;
	private String pay_SALE_DT;
	private String pay_STR_CODE;
	private String pay_TRXN_NO;
	private long pay_ZAN_AMT;
	private long pay_PAY_ZAN_AMT;
	private String pay_CANC_FLAG;
	private String pay_SALE_DT_;

	//파라미터 변수 선언
	String P_CORP_CODE_Param;
	String P_STR_CODE_Param;
	String P_SALE_DT_Param;

	//ReportHandler 생성자 함수
	ReportHandler(PageContext pageContext, HttpServletRequest request, HttpServletResponse response, Object[] userObj, HttpParameterDecoder decoder){
		this.pageContext = pageContext;
		this.request = request;
		this.response = response;
		this.userObj = userObj;
		this.decoder = decoder;
	}

	//ReportHandler 서비스 함수
	void service(JspWriter out) throws Exception{
		try{    //try 구문
			//변수 초기화
			this.out = out;
			nMaxPage = 0;   //nMaxPage 초기화

			nBandRepeatType=0;
			nBandWidth=0;
			nBandOffset=0;
			nYBandStart=0;
			nYBandEnd=0;
			nHorRepeatNum=0;
			nHorRepeatCnt=0;

			manager = new AIScriptManager(request, response, pageContext, out, logger, null);

			ServletContext context = pageContext.getServletContext();
			String temp = null;
			if(!context.getContextPath().equals("/"))
			temp = request.getRequestURI().replace(context.getContextPath(), "");
			else
			temp = request.getRequestURI();

			String path = temp.replace(".jsp", ".style");

			//셀 Rect, Style 값 저장
			setCellInfoMap();

			//파라미터 설정 함수 호출
			setParam();
			if(manager.open(reportMode, context.getRealPath(path)))
			{
				//스크립트 헤더 함수 호출
				getScriptHeader("A4", "2100x2970", "9", "HORIZONTAL", "14 0 14 28");

				//고정 데이터 초기화 함수 호출
				initConstVarient();

				//Connection 및 Statement 객체 생성 함수 호출
				createConnAndStateObject();

				//쿼리문 초기화 함수 호출
				initSQLConst();

				//쉬트 함수 호출
				//SHEET=Sheet1   FRAME=0 함수 호출
				executeSheet10();

				//---------------스크립트 종료---------------
				manager.scriptWrite("/AIReport", "", "", false);
				manager.close();
			}
		}catch(Throwable t){    //catch 구문
			logger.error("---service function exception raised---");
			logger.error(t.toString());
			throw (new AIException(t.toString(),t.getCause()));
		}finally{    //finally 구문
			if(manager.reportFile!=null)
			manager.reportFile.close();

			//DataSet Close
			cleanup(pay, stat_pay, null, null);
			cleanup(param, stat_param, null, null);
			cleanup(null, null, null, conn_retail);
		}    //end try
	}

	//-----쉬트 함수-----
	//-----SHEET=Sheet1   FRAME=Frame0 Start
	//-----폼 형식 : 상대 양식
	private void executeSheet10( ) throws Exception{
		//쉬트 초기화 함수 호출
		getSheetPaperInfo("A4", "2100x2970", "9", "VERTICAL", "0 0 0 28");
		initSheetVariant(13, 27, 585, 801, true);

		//시작 페이지 번호 출력
		pageWrite(nPageNum);

		//밴드 함수 호출
		getScriptFromsh1_h1(true, true);    //머리글 밴드 호출
		getScriptFromsh1_v2(true, true);    //Void 밴드 호출

		//페이지 및 좌표 설정
		nMaxPage=(int)MAX((long)nMaxPage, (long)nPageNum);    //생성된 최대 페이지 번호 구하기

		//자식 쉬트 호출
		//SHEET=Sheet2   FRAME=0 함수 호출
		executeSheet20();
	}

	//-----SHEET=Sheet2   FRAME=Frame0 Start
	//-----폼 형식 : 상대 양식
	private void executeSheet20( ) throws Exception{
		//쉬트 초기화 함수 호출
		initChildSheetVariant(13, 27, 585, 801, false, false);

		//시작 페이지 번호 출력
		pageWrite(nPageNum);

		//밴드 함수 호출
		getScriptFromsh2_v2(true, true);    //Void 밴드 호출
		getScriptFromsh1_v1(true, true);    //Void 밴드 호출
		getScriptFromsh1_f1(true);    //반복 밴드 호출

		//페이지 및 좌표 설정
		nMaxPage=(int)MAX((long)nMaxPage, (long)nPageNum);    //생성된 최대 페이지 번호 구하기
	}

	//-----밴드 함수-----
	//----sh1_h1 HeaderBand Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : sh1_h1
	//----밴드 종류 : 머리글 밴드
	//----bIsFrist : 쉬트 함수에서 최초로 호출될 때 true, 페이지 스킵 함수에서 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	private void getScriptFromsh1_h1(boolean bIsFirst, boolean bIsPrint) throws Exception{
		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//DataSet 객체 생성
			//ResultSet param 객체의 생성
			if(param==null){
				param = stat_param.executeQuery();
			}else{
				param.beforeFirst();
			}

			//데이터 fetch
			if(param.next()){
				setFieldVariableFromparam();	//ResultSet param에서 필드 값 설정
			}else{
				setFieldInitFromparam();	//ResultSet param의 필드 값 초기화
			}

			//데이터 변수 초기화
			AI_STRING_OBJ3="";

			//데이터 변수 할당
			AI_STRING_OBJ3 = param_T;
		}   //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 함수 호출
			writeScriptsh1_h1();
		}   //end if(bIsPrint)
	}

	//----sh1_v2 VoidBand Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : sh1_v2
	//----밴드 종류 : Void 밴드
	//----bIsFrist : 부모 밴드 함수나 쉬트 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	//----nRepeatCnt : 부모 반복 밴드 수행 횟수와 연동 옵션 설정시 void 밴드가 수행할 반복 횟수 전달
	private void getScriptFromsh1_v2(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=40;    //밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//DataSet 객체 생성
			//ResultSet param 객체의 생성
			if(param==null){
				param = stat_param.executeQuery();
			}else{
				param.beforeFirst();
			}

			//데이터 fetch
			if(param.next()){
				setFieldVariableFromparam();	//ResultSet param에서 필드 값 설정
			}else{
				setFieldInitFromparam();	//ResultSet param의 필드 값 초기화
			}

			//데이터 변수 초기화
			sheet10_A2="";
			sheet10_D2="";

			//데이터 변수 할당
			sheet10_A1="외상매출발생";
			sheet10_A2 = param_STR_NAME;
			sheet10_D2 = param_SALE_DT;
		}    //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScriptsh1_v2();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//----sh2_v2 VoidBand Start----
	//----소속 쉬트 : SHEET=Sheet2    FRAME=Frame0
	//----밴드 이름 : sh2_v2
	//----밴드 종류 : Void 밴드
	//----bIsFrist : 부모 밴드 함수나 쉬트 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	//----nRepeatCnt : 부모 반복 밴드 수행 횟수와 연동 옵션 설정시 void 밴드가 수행할 반복 횟수 전달
	private void getScriptFromsh2_v2(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=3;    //밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
		}    //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 함수 호출
			//Empty Row만으로 구성되어 출력 위치를 조정하기 위한 VoidBand 함수 호출
			voidBandNoneData(nBandHeight, 10);
		}   //end if(bIsPrint)
	}

	//----sh1_v1 VoidBand Start----
	//----소속 쉬트 : SHEET=Sheet2    FRAME=Frame0
	//----밴드 이름 : sh1_v1
	//----밴드 종류 : Void 밴드
	//----bIsFrist : 부모 밴드 함수나 쉬트 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	//----nRepeatCnt : 부모 반복 밴드 수행 횟수와 연동 옵션 설정시 void 밴드가 수행할 반복 횟수 전달
	private void getScriptFromsh1_v1(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=18;    //밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//데이터 변수 할당
			sheet20_A2="회계코드";
			sheet20_B2="회원번호";
			sheet20_C2="회원명";
			sheet20_D2="매출일자";
			sheet20_E2="매출구분";
			sheet20_F2="POS";
			sheet20_G2="거래번호";
			sheet20_H2="매출액";
		}    //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScriptsh1_v1();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//----sh1_f1_sub ConditionBand Start----
	//----소속 쉬트 : SHEET=Sheet2    FRAME=Frame0
	//----밴드 이름 : sh1_f1_sub
	//----밴드 종류 : 조건 밴드
	//----bIsFrist : 부모 밴드 함수에서 최초로 호출될 때 true
	//----bIsLast : 부모 밴드 함수에서 마지막으로 호출될 때 true
	//----bIsTrue : 부모 밴드 함수에서 조건 밴드 출력 조건 플래그 값
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	private void getScriptFromsh1_f1_sub(boolean bIsFirst, boolean bIsLast, boolean bIsTrue, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=19;	//밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//데이터 변수 초기화
			sheet20_H4=0L;
		}   //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsTrue){   //조건 밴드 출력 플래그 값이 true인 경우
			//조건 밴드의 참 값
			if(bIsPrint){   //WriteBandObj() 함수 대체 코드
				if(isPageSkip(nYCurPos+nBandHeight)){
					pageSkipVirtualMergesh1_f1();
					pageSkip(10);
				}
				writeScriptsh1_f1_sub();	//스크립트문 출력
				nYCurPos=nYCurPos+nBandHeight;
				sheet20_H4=0L;
			}
		}else{   //조건 밴드 출력 플래그 값이 false인 경우
		}   //end if(bIsTrue)

		if(!bIsLast){   //bIsLast가 false인 경우 - 조건 밴드의 수식 계산
			//데이터 변수 할당
			sheet20_A4="소계";
			sheet20_H4=(long)SUM(sheet20_H3, sheet20_H4);
		}   //end if(!bIsLast)
	}

	//----sh_f1_s1 ConditionBand Start----
	//----소속 쉬트 : SHEET=Sheet2    FRAME=Frame0
	//----밴드 이름 : sh_f1_s1
	//----밴드 종류 : 조건 밴드
	//----bIsFrist : 부모 밴드 함수에서 최초로 호출될 때 true
	//----bIsLast : 부모 밴드 함수에서 마지막으로 호출될 때 true
	//----bIsTrue : 부모 밴드 함수에서 조건 밴드 출력 조건 플래그 값
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	private void getScriptFromsh_f1_s1(boolean bIsFirst, boolean bIsLast, boolean bIsTrue, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=18;	//밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//데이터 변수 초기화
			sheet20_H5=0L;
		}   //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsTrue){   //조건 밴드 출력 플래그 값이 true인 경우
			//조건 밴드의 참 값
			if(bIsPrint){   //WriteBandObj() 함수 대체 코드
				if(isPageSkip(nYCurPos+nBandHeight)){
					pageSkipVirtualMergesh1_f1();
					pageSkip(10);
				}
				writeScriptsh_f1_s1();	//스크립트문 출력
				nYCurPos=nYCurPos+nBandHeight;
				sheet20_H5=0L;
			}
		}else{   //조건 밴드 출력 플래그 값이 false인 경우
		}   //end if(bIsTrue)

		if(!bIsLast){   //bIsLast가 false인 경우 - 조건 밴드의 수식 계산
			//데이터 변수 할당
			sheet20_A5="합계";
			sheet20_H5=(long)SUM(sheet20_H3, sheet20_H5);
		}   //end if(!bIsLast)
	}

	//-----sh1_f1 RepeatBand Start-----
	//-----소속 쉬트 : SHEET=Sheet2   FRAME=Frame0
	//-----밴드 이름 : sh1_f1
	//-----밴드 종류 : 반복 밴드
	//-----bIsPrint : 감추기 속성 설정 여부 true면 출력, false면 스크립트를 생성하지 않음
	private void getScriptFromsh1_f1(boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=18;    //밴드 출력 높이
		boolean bIsFirst=true;
		boolean bIsTrue_sh1_f1_sub=false;   //sh1_f1_sub 조건 밴드 플래그 선언
		boolean bIsTrue_sh_f1_s1=false;   //sh_f1_s1 조건 밴드 플래그 선언

		//데이터 변수 초기화
		sheet20_A3_Buf=null;
		sheet20_A3_Flag=true;
		sheet20_A3="";
		sheet20_B3_Buf=null;
		sheet20_B3_Flag=true;
		sheet20_B3="";
		sheet20_C3_Buf=null;
		sheet20_C3_Flag=true;
		sheet20_C3="";
		sheet20_D3="";
		sheet20_E3="";
		sheet20_F3="";
		sheet20_G3="";
		sheet20_H3=0L;
		bEnabledVirtualMerge_sh1_f1=false;

		//DataSet 객체 생성
		//ResultSet pay 객체의 생성
		if(pay==null){
			pay = stat_pay.executeQuery();
		}else{
			pay.beforeFirst();
		}

		//--while Loop Start--##
		while(pay.next()){   //자동으로 생성되는 반복 밴드의 루프문
			//데이터 fetch
			setFieldVariableFrompay();	//RecordSet pay에서 필드 값 설정

			//조건 밴드 출력 조건문
			bIsBeforePageSkip=false;
			if(!pay_CUST_NO.equals(sheet20_B3)){    //sh1_f1_sub 밴드 조건문
				bIsTrue_sh1_f1_sub=true;
			}else{
				bIsTrue_sh1_f1_sub=false;
			}

			if(bIsFirst){   //밴드 호출 후 루프 내에서 한번 만 실행되는 코드
				//조건 플래그 초기화
				bIsTrue_sh1_f1_sub=false;    //sh1_f1_sub 조건 밴드 플래그 초기화
				bIsTrue_sh_f1_s1=false;    //sh_f1_s1 조건 밴드 플래그 초기화
			}   //end if(bIsFirst)

			//데이터 변수 할당
			if(!sheet20_A3.equals(pay_ACCT_DEPT)){
				if(!bIsFirst){
					sheet20_A3_Buf = sheet20_A3;
					sheet20_A3_Flag=true;
				}
				sheet20_A3=pay_ACCT_DEPT;
			}
			if(!sheet20_B3.equals(pay_CUST_NO)){
				if(!bIsFirst){
					sheet20_B3_Buf = sheet20_B3;
					sheet20_B3_Flag=true;
				}
				sheet20_B3=pay_CUST_NO;
			}
			if(!sheet20_C3.equals(pay_CUST_NAME)){
				if(!bIsFirst){
					sheet20_C3_Buf = sheet20_C3;
					sheet20_C3_Flag=true;
				}
				sheet20_C3=pay_CUST_NAME;
			}
			sheet20_D3 = pay_SALE_DT_;
			sheet20_E3 = pay_CANC_FLAG;
			sheet20_F3 = pay_POS_NO;
			sheet20_G3 = pay_TRXN_NO;
			sheet20_H3 = pay_PAY_ZAN_AMT;

			//루프 내부 가상병합 출력 함수 호출
			if(bIsPrint){
				writeScriptVirtualMergesh1_f1();
			}

			//루프 내부 조건밴드 및 스타일 함수 호출
			getScriptFromsh1_f1_sub(bIsFirst, false, bIsTrue_sh1_f1_sub, true);   //sh1_f1_sub 조건 밴드 호출
			getScriptFromsh_f1_s1(bIsFirst, false, bIsTrue_sh_f1_s1, true);   //sh_f1_s1 조건 밴드 호출

			//AI 스크립트 출력
			if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
				if(isPageSkip(nYCurPos+nBandHeight)){   //스크립트 출력 영역 검사
					//가상병합 출력 및 한번만 데이터 Reset
					pageSkipVirtualMergesh1_f1();

					//페이지 스킵 함수 호출
					pageSkip(10);
				}   //end if(page skip test)

				//스크립트 출력 함수 호출
				writeScriptsh1_f1();

				//페이지 연결 출력 및 가상병합 플래그 Reset
				if(sheet20_A3_Flag){
					sheet20_A3_YPos=nYCurPos;
					sheet20_A3_Buf=null;
					sheet20_A3_Flag=false;
				}
				if(sheet20_B3_Flag){
					sheet20_B3_YPos=nYCurPos;
					sheet20_B3_Buf=null;
					sheet20_B3_Flag=false;
				}
				if(sheet20_C3_Flag){
					sheet20_C3_YPos=nYCurPos;
					sheet20_C3_Buf=null;
					sheet20_C3_Flag=false;
				}
				bEnabledVirtualMerge_sh1_f1=true;

				//다음 출력 좌표 설정
				nYCurPos=nYCurPos+nBandHeight;
			}   //end if(bIsPrint)

			//bIsFirst 및 출력 라인 설정
			bIsFirst=false;
		}   //while end

		if(bIsFirst){   //while 루프가 실행되지 않은 경우
		} else {   //while 루프가 실행된 경우
			//루프 외부 가상병합 출력 함수 호출
			sheet20_A3_Buf = sheet20_A3;
			sheet20_B3_Buf = sheet20_B3;
			sheet20_C3_Buf = sheet20_C3;
			if(bIsPrint){
				writeScriptVirtualMergesh1_f1();
			}

			//루프 외부 조건밴드 및 스타일 함수 호출
			getScriptFromsh1_f1_sub(bIsFirst, true, true, true);   //sh1_f1_sub 조건 밴드 호출
			getScriptFromsh_f1_s1(bIsFirst, true, true, true);   //sh_f1_s1 조건 밴드 호출
		}   //루프 외부 end if(bIsFirst)
	}

	//----sh1_f1 반복밴드 Page Skip시 가상 병합 데이터 설정 및 출력 함수----
	private void pageSkipVirtualMergesh1_f1(  ) throws Exception{
		//가상 병합 데이터 설정 및 출력
		if(bEnabledVirtualMerge_sh1_f1){
			if(sheet20_A3_Buf==null){
				sheet20_A3_Buf = sheet20_A3;
			}else{
				sheet20_A3_Buf=null;
			}
			sheet20_A3_Flag=true;
			if(sheet20_B3_Buf==null){
				sheet20_B3_Buf = sheet20_B3;
			}else{
				sheet20_B3_Buf=null;
			}
			sheet20_B3_Flag=true;
			if(sheet20_C3_Buf==null){
				sheet20_C3_Buf = sheet20_C3;
			}else{
				sheet20_C3_Buf=null;
			}
			sheet20_C3_Flag=true;
			writeScriptVirtualMergesh1_f1();
		}
	}

	//-----스크립트 출력 함수-----
	//----sh1_h1 스크립트 문 출력 함수----
	private void writeScriptsh1_h1( ) throws Exception{
		//스크립트문 생성
		objectWrite(DRAW_OBJECT, 533, 15, 44, 9, AI_STRING_OBJ2, "AI_STRING_OBJ2", "draw_style_0");
		objectWrite(DRAW_OBJECT, 478, 13, 42, 18, AI_STRING_OBJ3, "AI_STRING_OBJ3", "draw_style_0");
	}

	//----sh1_v2 스크립트 문 출력 함수----
	private void writeScriptsh1_v2( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_A1"), nYCurPos+mapTop.get("sheet10_A1"), mapWidth.get("sheet10_A1"), mapHeight.get("sheet10_A1"), sheet10_A1, "sheet10_A1", mapStyle.get("sheet10_A1"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_A2"), nYCurPos+mapTop.get("sheet10_A2"), mapWidth.get("sheet10_A2"), mapHeight.get("sheet10_A2"), sheet10_A2, "sheet10_A2", mapStyle.get("sheet10_A2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_D2"), nYCurPos+mapTop.get("sheet10_D2"), mapWidth.get("sheet10_D2"), mapHeight.get("sheet10_D2"), sheet10_D2, "sheet10_D2", mapStyle.get("sheet10_D2"));
	}

	//----sh1_v1 스크립트 문 출력 함수----
	private void writeScriptsh1_v1( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_A2"), nYCurPos+mapTop.get("sheet20_A2"), mapWidth.get("sheet20_A2"), mapHeight.get("sheet20_A2"), sheet20_A2, "sheet20_A2", mapStyle.get("sheet20_A2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_B2"), nYCurPos+mapTop.get("sheet20_B2"), mapWidth.get("sheet20_B2"), mapHeight.get("sheet20_B2"), sheet20_B2, "sheet20_B2", mapStyle.get("sheet20_B2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_C2"), nYCurPos+mapTop.get("sheet20_C2"), mapWidth.get("sheet20_C2"), mapHeight.get("sheet20_C2"), sheet20_C2, "sheet20_C2", mapStyle.get("sheet20_C2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_D2"), nYCurPos+mapTop.get("sheet20_D2"), mapWidth.get("sheet20_D2"), mapHeight.get("sheet20_D2"), sheet20_D2, "sheet20_D2", mapStyle.get("sheet20_D2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_E2"), nYCurPos+mapTop.get("sheet20_E2"), mapWidth.get("sheet20_E2"), mapHeight.get("sheet20_E2"), sheet20_E2, "sheet20_E2", mapStyle.get("sheet20_E2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_F2"), nYCurPos+mapTop.get("sheet20_F2"), mapWidth.get("sheet20_F2"), mapHeight.get("sheet20_F2"), sheet20_F2, "sheet20_F2", mapStyle.get("sheet20_F2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_G2"), nYCurPos+mapTop.get("sheet20_G2"), mapWidth.get("sheet20_G2"), mapHeight.get("sheet20_G2"), sheet20_G2, "sheet20_G2", mapStyle.get("sheet20_G2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_H2"), nYCurPos+mapTop.get("sheet20_H2"), mapWidth.get("sheet20_H2"), mapHeight.get("sheet20_H2"), sheet20_H2, "sheet20_H2", mapStyle.get("sheet20_H2"));
	}

	//----sh1_f1_sub 스크립트 문 출력 함수----
	private void writeScriptsh1_f1_sub( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_A4"), nYCurPos+mapTop.get("sheet20_A4"), mapWidth.get("sheet20_A4"), mapHeight.get("sheet20_A4"), sheet20_A4, "sheet20_A4", mapStyle.get("sheet20_A4"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_H4"), nYCurPos+mapTop.get("sheet20_H4"), mapWidth.get("sheet20_H4"), mapHeight.get("sheet20_H4"), String.valueOf(sheet20_H4), "sheet20_H4", mapStyle.get("sheet20_H4"));
	}

	//----sh_f1_s1 스크립트 문 출력 함수----
	private void writeScriptsh_f1_s1( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_A5"), nYCurPos+mapTop.get("sheet20_A5"), mapWidth.get("sheet20_A5"), mapHeight.get("sheet20_A5"), sheet20_A5, "sheet20_A5", mapStyle.get("sheet20_A5"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_H5"), nYCurPos+mapTop.get("sheet20_H5"), mapWidth.get("sheet20_H5"), mapHeight.get("sheet20_H5"), String.valueOf(sheet20_H5), "sheet20_H5", mapStyle.get("sheet20_H5"));
	}

	//----sh1_f1 스크립트 문 출력 함수----
	private void writeScriptsh1_f1(  ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_D3"), nYCurPos+mapTop.get("sheet20_D3"), mapWidth.get("sheet20_D3"), mapHeight.get("sheet20_D3"), sheet20_D3, "sheet20_D3", mapStyle.get("sheet20_D3"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_E3"), nYCurPos+mapTop.get("sheet20_E3"), mapWidth.get("sheet20_E3"), mapHeight.get("sheet20_E3"), sheet20_E3, "sheet20_E3", mapStyle.get("sheet20_E3"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_F3"), nYCurPos+mapTop.get("sheet20_F3"), mapWidth.get("sheet20_F3"), mapHeight.get("sheet20_F3"), sheet20_F3, "sheet20_F3", mapStyle.get("sheet20_F3"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_G3"), nYCurPos+mapTop.get("sheet20_G3"), mapWidth.get("sheet20_G3"), mapHeight.get("sheet20_G3"), sheet20_G3, "sheet20_G3", mapStyle.get("sheet20_G3"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_H3"), nYCurPos+mapTop.get("sheet20_H3"), mapWidth.get("sheet20_H3"), mapHeight.get("sheet20_H3"), String.valueOf(sheet20_H3), "sheet20_H3", mapStyle.get("sheet20_H3"));
	}

	//----sh1_f1 VirtualMerge 스크립트 문 출력 함수----
	private void writeScriptVirtualMergesh1_f1(  ) throws Exception{
		//가상병합 스크립트문 생성
		if(sheet20_A3_Buf != null){
			objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_A3"), sheet20_A3_YPos, mapWidth.get("sheet20_A3"), nYCurPos-sheet20_A3_YPos, sheet20_A3_Buf, "sheet20_A3", mapStyle.get("sheet20_A3"));
		}
		if(sheet20_B3_Buf != null){
			objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_B3"), sheet20_B3_YPos, mapWidth.get("sheet20_B3"), nYCurPos-sheet20_B3_YPos, sheet20_B3_Buf, "sheet20_B3", mapStyle.get("sheet20_B3"));
		}
		if(sheet20_C3_Buf != null){
			objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_C3"), sheet20_C3_YPos, mapWidth.get("sheet20_C3"), nYCurPos-sheet20_C3_YPos, sheet20_C3_Buf, "sheet20_C3", mapStyle.get("sheet20_C3"));
		}
	}

	private void getBgImageScriptEx(int nIndex) throws Exception{
	}

	//-----Connection 및 Statement 객체 생성 함수-----
	private void createConnAndStateObject() throws Exception{
		//retail Connection 객체 생성
		Class.forName("oracle.jdbc.OracleDriver");
		conn_retail = DriverManager.getConnection("jdbc:oracle:thin:@210.219.229.37:1521:umac", "UMACSM", "dbaor!@#");
	}

	//-----ResultSet, PreparedStatement, Connection, CallableStatement Close 함수-----
	private void cleanup(Object rs, PreparedStatement st, CallableStatement cs, Connection conn){
		if(rs != null){
			try{
				if(rs instanceof ResultSet){
					((ResultSet)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.AIDataSource){
					((com.activeintra.util.uds.AIDataSource)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.XMLSetHandler){
					((com.activeintra.util.uds.XMLSetHandler)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.CSVSetHandler){
					((com.activeintra.util.uds.CSVSetHandler)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.JSONSetHandler){
					((com.activeintra.util.uds.JSONSetHandler)rs).close();
				}
			}
			catch(SQLException e){
				logger.error(e);
			}
		}

		if(st != null){
			try{
				st.close();
			}
			catch(SQLException e){
				logger.error(e);
			}
		}

		if(cs != null){
			try{
				cs.close();
			}
			catch(SQLException e){
				logger.error(e);
			}
		}

		if(conn != null){
			try{
				conn.close();
			}
			catch(SQLException e){
				logger.error(e);
			}
		}
	}

	//-----SQL문 변수 초기화 함수-----
	private void initSQLConst() throws Exception {
		stat_param = initializer.configPreparedStatement("sql_param", mapParam, conn_retail, null);

		stat_pay = initializer.configPreparedStatement("sql_pay", mapParam, conn_retail, null);
	}

	//-----ResultSet 객체에서 필드 값 설정 함수-----
	//ResultSet param 객체에서 필드 값 설정 함수
	private void setFieldVariableFromparam() throws Exception{
		param_T = GetB(param.getString(1));
		param_STR_NAME = GetB(param.getString(2));
		param_SALE_DT = GetB(param.getString(3));
	}

	//ResultSet param 객체의 필드 값 초기화 함수
	private void setFieldInitFromparam(){
		param_T = "";
		param_STR_NAME = "";
		param_SALE_DT = "";
	}

	//ResultSet pay 객체에서 필드 값 설정 함수
	private void setFieldVariableFrompay() throws Exception{
		pay_CORP_CODE = GetB(pay.getString(1));
		pay_CUST_NO = GetB(pay.getString(2));
		pay_POS_NO = GetB(pay.getString(3));
		pay_CUST_NAME = GetB(pay.getString(4));
		pay_ACCT_DEPT = GetB(pay.getString(5));
		pay_STR_NAME = GetB(pay.getString(6));
		pay_PAY_AMT = pay.getLong(7);
		pay_SALE_DT = GetB(pay.getString(8));
		pay_STR_CODE = GetB(pay.getString(9));
		pay_TRXN_NO = GetB(pay.getString(10));
		pay_ZAN_AMT = pay.getLong(11);
		pay_PAY_ZAN_AMT = pay.getLong(12);
		pay_CANC_FLAG = GetB(pay.getString(13));
		pay_SALE_DT_ = GetB(pay.getString(14));
	}

	//ResultSet pay 객체의 필드 값 초기화 함수
	private void setFieldInitFrompay(){
		pay_CORP_CODE = "";
		pay_CUST_NO = "";
		pay_POS_NO = "";
		pay_CUST_NAME = "";
		pay_ACCT_DEPT = "";
		pay_STR_NAME = "";
		pay_PAY_AMT = 0L;
		pay_SALE_DT = "";
		pay_STR_CODE = "";
		pay_TRXN_NO = "";
		pay_ZAN_AMT = 0L;
		pay_PAY_ZAN_AMT = 0L;
		pay_CANC_FLAG = "";
		pay_SALE_DT_ = "";
	}

	//-----고정 데이터 초기화 함수-----
	private void initConstVarientEx(){
		AI_STRING_OBJ2="Page : #PAGE/#TOTALPAGE";
	}

	//-----공통 함수 선언-----
	//파라미터 설정 함수
	private void setParam() {
		//SetParam_AutoCode
		reportMode=decoder.getParameterB("reportMode");
		if(reportMode.equals("")) {
			reportMode="HTML";
		}
		manager.setParam("pdfFilename:" + pdfFilename + "," + "excelFilename:" + excelFilename + "," + decoder.getParameterB("reportParams"));

		//char data[] = {0x14};
		//String str = new String(data);
		mapParam = new HashMap<String, String>();

		P_CORP_CODE_Param=decoder.getParameterB("P_CORP_CODE");
		//P_CORP_CODE_Param=aiReplace(P_CORP_CODE_Param, str, "\n");
		mapParam.put("P_CORP_CODE", P_CORP_CODE_Param);

		P_STR_CODE_Param=decoder.getParameterB("P_STR_CODE");
		//P_STR_CODE_Param=aiReplace(P_STR_CODE_Param, str, "\n");
		mapParam.put("P_STR_CODE", P_STR_CODE_Param);

		P_SALE_DT_Param=decoder.getParameterB("P_SALE_DT");
		//P_SALE_DT_Param=aiReplace(P_SALE_DT_Param, str, "\n");
		mapParam.put("P_SALE_DT", P_SALE_DT_Param);
	}

	//상수 데이터 초기화 래퍼 함수
	private void initConstVarient() {
		//InitConstVarient_AutoCode
		initConstVarientEx();
	}

	//배경 이미지 출력 래퍼 함수
	private void getBgImageScript(int nIndex) throws Exception{
		//GetBgImageScript_AutoCode
		getBgImageScriptEx(nIndex);
	}

	//페이지 스킵 함수
	//페이지 스킵시 호출되는 함수로서 페이지 번호를 증가시키고 페이지 지시문 출력 그리고 Y좌표 초기화
	//매개변수에 따라 해당 쉬트의 배경 이미지, 머리글 밴드, 바닥글 밴드 함수 호출
	private void pageSkip(int nIndex) throws Exception{
		//PageSkip_AutoCode
		if(nBandRepeatType==1) {
			int tmpX;
			tmpX=nXCurPos+nBandWidth+nBandOffset;
			nHorRepeatCnt=nHorRepeatCnt+1;
			if(tmpX+nBandWidth>nXEndPos || nHorRepeatCnt==nHorRepeatNum) {
				nYBandStart=nYStartPos;
				nYBandEnd=0;
				nHorRepeatCnt=0;
			}else{
				if(nYBandEnd<nYCurPos) {
					nYBandEnd=nYCurPos;
				}
				nYCurPos=nYBandStart;
				nXCurPos=tmpX;
				return;
			}
		}

		nXCurPos=nXStartPos;
		nYCurPos=nYStartPos;
		nPageNum=nPageNum+1;
		pageWrite(nPageNum);

		switch(nIndex){
			case 10:		//SHEET=Sheet=1   FRAME=0에서 페이지 스킵시
			getScriptFromsh1_h1(false, true);		//머리글 밴드 호출
			break;
		}
	}

	//페이지 스킵이 필요한지 검사하는 함수
	private boolean isPageSkip(int nTestPos){
		//IsPageSkip_AutoCode
		if(nTestPos>nYEndPos){
			return true;
		}else{
			return false;
		}
	}

	//문자의 폭을 조사하여 데이터의 출력 높이를 자동적으로 조정하는 함수
	private int getPrintHeight(String data, int[] charWidth, int fontSize, int printWidth, int printHeight, int nMaxHeight, int horMargin, int vertMargin, String styleName) throws Exception {
		//GetPrintHeight_AutoCode
		if(data.equals(isEmpty)){
			return nMaxHeight;
		}
		if(!reportMode.equals("AIScript")) {
			printWidth+=horMargin;
			printHeight+=vertMargin;
			int needHeight=(int)TextHandler.wordWrapTextEx(printWidth, data, styleName, manager.getAIStyleInfo());

			if(needHeight>printHeight) {
				needHeight=needHeight-printHeight;
			}else{
				needHeight=0;
			}

			needHeight=(int)MAX((long)needHeight,(long)nMaxHeight);
			return needHeight;
		}
		else {
			int ch;
			int len = 95;
			int []width = new int[1];
			width[0] = 0;
			int asciiWidth = 0;
			int linePitch = (int)(fontSize*1.4);
			int height = linePitch;
			int size = data.length();
			int ascIndex=0;
			printWidth = printWidth*100;

			for (int i = 0; i < size; i++) {
				ch = data.charAt(i);

				if(ch<32 && !(ch==10 || ch==20 || ch==13)){
					continue;
				}

				if((ch>64 && ch<91) || (ch>96 && ch<123)) {
					if(asciiWidth==0){
						ascIndex=i;
					}

					asciiWidth += charWidth[ch-32];
					if (i==size-1){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i+1, linePitch, printWidth, width, asciiWidth);
					}
				} else if (ch==10 || ch==20 || ch==13) {
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						asciiWidth = 0;
					}

					width[0] = 0;
					height += linePitch;

					if (ch==13) {
						if ((i != size-1) && (10 == (int)data.charAt(i+1))) {
							i++;
						}
					}
				} else {
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						asciiWidth=0;
					}

					if(ch>=32 && ch<=127){
						width[0] += charWidth[ch-32];
						if (width[0] > printWidth) {
							if (ch==32)
							{
								width[0] = 0;
							}
							else
							{
								width[0] = charWidth[ch-32];
							}
							height += linePitch;
						}
					}else{
						width[0] += charWidth[len];
						if (width[0] > printWidth) {
							width[0] = charWidth[len];
							height += linePitch;
						}
					}
				}
			}

			if (height>printHeight) {
				height=height-printHeight;
			}else{
				height=0;
			}

			height = (int)MAX((long)height,(long)nMaxHeight);
			return height;
		}
	}

	//영문 단어의 폭을 문자별로 조사하여 데이터의 출력 높이를 조정하는 함수
	private int getWordWrapHeight(String data, int[] charWidth, int nStartIndex, int nEndIndex, int linePitch, int printWidth, int []width, int asciiWidth){
		//GetWordWrapHeight_AutoCode
		int ch;
		int height=0;

		if(asciiWidth>printWidth){
			for(int i=nStartIndex; i<nEndIndex; i++){
				ch=data.charAt(i);
				width[0]+=charWidth[ch-32];
				if(width[0]>printWidth){
					width[0]=charWidth[ch-32];
					height+=linePitch;
				}
			}
		}else{
			width[0]+=asciiWidth;
			if(width[0]>printWidth){
				width[0]=asciiWidth;
				height+=linePitch;
			}
		}

		return height;
	}

	//문자의 폭을 조사하여 데이터의 출력 높이를 자동적으로 조정하고 페이지 초과시 초과하는 데이터 절삭하는 함수
	private int getPrintHeightEx(String data, String[] strSplitData, int[] charWidth, int fontSize, int printWidth, int nExtHeight, int nMaxHeight, int horMargin, int vertMargin, String styleName) throws Exception {
		//GetPrintHeightEx_AutoCode
		if(!reportMode.equals("AIScript")) {
			strSplitData[0]="";
			strSplitData[1]="";
			printWidth+=horMargin;
			nExtHeight+=vertMargin;
			int needHeight=(int)TextHandler.wordWrapTextEx(printWidth, nExtHeight, data, strSplitData, styleName, manager.getAIStyleInfo());

			if(needHeight>nExtHeight) {
				needHeight=nExtHeight;
			}

			needHeight = (int)MAX((long)needHeight,(long)nMaxHeight);
			return needHeight;
		}
		else {
			int ch;
			int i;
			int len = 95;
			int []width = new int[1];
			width[0] = 0;
			int asciiWidth = 0;
			int linePitch = (int)(fontSize*1.4);
			int height = linePitch;
			int size = data.length();
			int ascIndex=0;
			boolean bSplit=false;
			strSplitData[0]="";
			strSplitData[1]="";
			printWidth = printWidth*100;

			for (i = 0; i < size; i++) {
				ch = data.charAt(i);

				if(ch<32 && !(ch==10 || ch==20 || ch==13)){
					continue;
				}

				if ((ch>64 && ch<91) || (ch>96 && ch<123)) {
					if(asciiWidth==0){
						ascIndex=i;
					}

					asciiWidth += charWidth[ch-32];
					if (i==size-1){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i+1, linePitch, printWidth, width, asciiWidth);
						if(height>nExtHeight){
							height=nExtHeight;
							bSplit=true;
							i=ascIndex;
							break;
						}
					}
				}else if (ch==10 || ch==20 || ch==13) {
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						if(height>nExtHeight){
							height=nExtHeight;
							bSplit=true;
							i=ascIndex;
							break;
						}
						asciiWidth = 0;
					}

					width[0] = 0;
					height += linePitch;
					if (ch==13){
						if ((i != size-1) && (10 == (int)data.charAt(i+1))) {
							i++;
						}
					}

					if(height>nExtHeight){
						height=nExtHeight;
						if(i!=size-1){
							bSplit=true;
							i++;
						}
						break;
					}
				}else{
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						if(height>nExtHeight){
							height=nExtHeight;
							bSplit=true;
							i=ascIndex;
							break;
						}
						asciiWidth=0;
					}

					if(ch>=32 && ch<=127){
						width[0] += charWidth[ch-32];
						if (width[0] > printWidth) {
							if (ch==32)
							{
								width[0] = 0;
							}
							else
							{
								width[0] = charWidth[ch-32];
							}
							height += linePitch;
						}
					}else{
						width[0] += charWidth[len];
						if (width[0] > printWidth) {
							width[0] = charWidth[len];
							height += linePitch;
						}
					}

					if(height>nExtHeight){
						height=nExtHeight;
						bSplit=true;
						break;
					}
				}
			}

			if(bSplit){
				strSplitData[0]=data.substring(0, i);
				strSplitData[1]=data.substring(i);
			}

			height = (int)MAX((long)height,(long)nMaxHeight);
			return height;
		}
	}

	//스크립트 헤더 출력 함수
	private void getScriptHeader(String paper, String size, String value, String orient, String margin) throws Exception{
		//GetScriptHeader_AutoCode
		manager.scriptWrite("AIReport", "scriptVersion|docVersion|style|title", "32|54|daySalesSettlementPayPrint.style|회원매출상세내역현황", false);
	}

	private void getSheetPaperInfo(String paper, String size, String value, String orient, String margin) throws Exception{
		//GetSheetPaperInfo_AutoCode
		manager.scriptWrite("PaperInfo", "name|size|value|orientation|margin", paper+"|"+size+"|"+value+"|"+orient+"|"+margin, true);
	}

	private void initSheetVariant(int constStartX, int constStartY, int constEndX, int constEndY, boolean bFirstFrame){
		//InitSheetVariant_AutoCode
		if(bFirstFrame){
			nStartPage=nMaxPage+1;
			nYLastPos=0;
		}
		nPageNum=nStartPage;
		nYStartPos=constStartY;
		nYEndPos=constEndY;
		nYCurPos=nYStartPos;
		nXStartPos=constStartX;
		nXEndPos=constEndX;
		CELL_OBJECT=0;
		DRAW_OBJECT=1;
		nXCurPos=nXStartPos;
	}

	private void initChildSheetVariant(int constStartX, int constStartY, int constEndX, int constEndY, boolean bIsMultiFrame, boolean bIsFirstFrame){
		//InitChildSheetVariant_AutoCode
		nXStartPos=constStartX;
		nXEndPos=constEndX;
		nXCurPos=nXStartPos;
		nYStartPos=constStartY;
		nYEndPos=constEndY;

		if(bIsMultiFrame){
			if(bIsFirstFrame){
				nStartPage=nPageNum;
				nYSavePos=nYCurPos;
				nYLastPos=0;
			}else{
				nPageNum=nStartPage;
				nYCurPos=nYSavePos;
			}
		}else{
			nStartPage=nPageNum;
		}
	}

	//Empty Row만으로 구성되어 출력 위치를 조정하기 위한 VoidBand 함수
	//nRangePos - VoidBand의 출력 영역
	//nIndex - PageSkip 함수 호출시 전달할 쉬트 인덱스
	private boolean voidBandNoneData(int nRangePos, int nIndex) throws Exception{
		//VoidBandNoneData_AutoCode
		int nTestPos;
		nTestPos=nYCurPos+nRangePos;
		if(isPageSkip(nTestPos)){
			pageSkip(nIndex);
			return true;
		}else{
			nYCurPos=nYCurPos+nRangePos;
			return false;
		}
	}

	private String Get0(String str){
		//Get0_AutoCode
		if(str==null){
			return "0";
		}else{
			if(str.equals("")){
				return "0";
			}else{
				return str;
			}
		}
	}

	private String GetB(String str){
		//GetB_AutoCode
		if(str==null){
			return "";
		}else{
			return str;
		}
	}

	private double SUM(double accVal, double tmpVal){
		//SUM(double, double)_AutoCode
		return(accVal+tmpVal);
	}

	private double SUM(double accVal, long tmpVal){
		//SUM(double, long)_AutoCode
		return(accVal+(double)tmpVal);
	}

	private long SUM(long accVal, long tmpVal){
		//SUM(long, long)_AutoCode
		return(accVal+tmpVal);
	}

	private double SUM(long accVal, double tmpVal){
		//SUM(long, double)_AutoCode
		return((double)accVal+tmpVal);
	}

	private long COUNT(long accuCNT){
		//COUNT_AutoCode
		return ++accuCNT;
	}

	private long MIN(long maxV, long maxTempV){
		//MIN(long, long)_AutoCode
		if(maxV<=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MIN(long maxV, double maxTempV){
		//MIN(long, double)_AutoCode
		if((double)maxV<=maxTempV){return (double)maxV;}
		else{return maxTempV;}
	}

	private double MIN(double maxV, double maxTempV){
		//MIN(double, double)_AutoCode
		if(maxV<=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MIN(double maxV, long maxTempV){
		//MIN(double, long)_AutoCode
		if(maxV<=maxTempV){return maxV;}
		else{return (double)maxTempV;}
	}

	private long MAX(long maxV, long maxTempV){
		//MAX(long, long)_AutoCode
		if(maxV>=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MAX(long maxV, double maxTempV){
		//MAX(long, double)_AutoCode
		if((double)maxV>=maxTempV){return (double)maxV;}
		else{return maxTempV;}
	}

	private double MAX(double maxV, double maxTempV){
		//MAX(double, double)_AutoCode
		if(maxV>=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MAX(double maxV, long maxTempV){
		//MAX(double, long)_AutoCode
		if(maxV>=maxTempV){return maxV;}
		else{return (double)maxTempV;}
	}

	private double AVG(double sumVal, long cntVal){
		//AVG(double, long)_AutoCode
		return(sumVal/cntVal);
	}

	private double AVG(long sumVal, long cntVal){
		//AVG(long, long)_AutoCode
		return((double)sumVal/(double)cntVal);
	}

	private String aiReplace(String strAll, String strSrc, String strDest) {
		//AIReplace_AutoCode
		int st = 0, ed = 0;
		final int size = strAll.length();
		ed = strAll.indexOf(strSrc);
		if (ed == -1) return strAll;

		StringBuffer buf = new StringBuffer(size);
		final int len =  strSrc.length();
		do {
			buf.append(strAll.substring(st, ed));
			buf.append(strDest);
			ed += len;
			st = ed;
		} while ((ed = strAll.indexOf(strSrc, ed)) != -1);
		if (st < size) {
			buf.append(strAll.substring(st));
		}
		return buf.toString();
	}

	private String toDate() {
		//ToDate_AutoCode
		SimpleDateFormat dateFormat=new SimpleDateFormat("'#SERVERDATE#'yyyy/MM/dd/HH/mm/ss");
		java.util.Date currentDate = new java.util.Date();
		return dateFormat.format(currentDate);
	}

	final String toKor (String en){
		//ToKor_AutoCode
		if(en==null){
			return "";
		}
		try{
			return new String(en.getBytes("ISO-8859-1"), "utf-8");
		}catch(UnsupportedEncodingException e){return en;}
	}

	private void objectWrite(int type, int left, int top, int width, int height, String data, String name, String style) throws Exception {
		//ObjectWrite_AutoCode
		manager.scriptWrite(type, left, top, width, height, data, name, style);
	}

	private void propertyWrite(int type, String name, String property, String style) throws Exception {
		//PropertyWrite_AutoCode
		manager.scriptWrite(type, name, property, style);
	}

	private void pageWrite(int pageNum) throws Exception {
		//PageWrite_AutoCode
		manager.scriptWrite("Page", "number", Integer.toString(pageNum), true);
	}

	private void objectCellWrite(String name, String data, int nMoveX, int nMoveY) throws Exception {
		objectWrite(CELL_OBJECT, nMoveX+(nXCurPos+mapLeft.get(name)), nMoveY+(nYCurPos+mapTop.get(name)), mapWidth.get(name), mapHeight.get(name), data, name, mapStyle.get(name));
	}

	public String checkParam(String param) {
		param = param.replace("'", "");
		param = param.replace(";", "");
		param = param.replace("|", "");
		param = param.replace(":", "");
		param = param.replace("+", "");
		param = param.replace("\"", "");
		param = param.replace("\\", "");
		param = param.replace("--", "");
		param = param.replace("/", "");
		param = param.replaceAll("(?i)select", "");
		param = param.replaceAll("(?i)union", "");
		param = param.replaceAll("(?i)delete", "");
		param = param.replaceAll("(?i)update", "");
		param = param.replaceAll("(?i)insert", "");
		param = param.replaceAll("(?i)create", "");
		param = param.replaceAll("(?i)alter", "");
		param = param.replaceAll("(?i)drop", "");
		param = param.replaceAll("(?i)grant", "");
		param = param.replaceAll("(?i)revoke", "");
		param = param.replaceAll("(?i)merge", "");
		return param;
	}

	public String checkAITag(String strText) {
		strText = strText.replace("AI{P}", "^");
		strText = strText.replace("AI{F}", "@");
		strText = strText.replace("AI{S}", "#");
		strText = strText.replace("AI{E}", "=");
		return strText;
	}

	//셀 Rect, Style값 Map 저장
	public void setCellInfoMap_Internal(String name, int left, int top, int width, int height, String style) throws Exception {
		if( left != -1 ) {
			mapLeft.put(name, left);
		}
		if( top != -1 ) {
			mapTop.put(name, top);
		}
		if( width != -1 ) {
			mapWidth.put(name, width);
		}
		if( height != -1 ) {
			mapHeight.put(name, height);
		}
		if( style != null && !style.equals("") ) {
			mapStyle.put(name, style);
		}
	}

	//셀 Rect, Style값 저장
	public void setCellInfoMap() throws Exception {
		mapLeft = new HashMap<String, Integer>();
		mapTop = new HashMap<String, Integer>();
		mapWidth = new HashMap<String, Integer>();
		mapHeight = new HashMap<String, Integer>();
		mapStyle = new HashMap<String, String>();
		setCellInfoMap_Internal("sheet10_A1", 0, 0, 572, 22, "cell_style_0");
		setCellInfoMap_Internal("sheet10_A2", 0, 22, 80, 18, "cell_style_1");
		setCellInfoMap_Internal("sheet10_D2", 240, 22, 80, 18, "cell_style_1");
		setCellInfoMap_Internal("sheet20_A2", 0, 0, 38, 18, "cell_style_2");
		setCellInfoMap_Internal("sheet20_B2", 38, 0, 38, 18, "cell_style_3");
		setCellInfoMap_Internal("sheet20_C2", 76, 0, 192, 18, "cell_style_4");
		setCellInfoMap_Internal("sheet20_D2", 268, 0, 52, 18, "cell_style_4");
		setCellInfoMap_Internal("sheet20_E2", 320, 0, 52, 18, "cell_style_4");
		setCellInfoMap_Internal("sheet20_F2", 372, 0, 38, 18, "cell_style_4");
		setCellInfoMap_Internal("sheet20_G2", 410, 0, 52, 18, "cell_style_4");
		setCellInfoMap_Internal("sheet20_H2", 462, 0, 110, 18, "cell_style_4");
		setCellInfoMap_Internal("sheet20_A3", 0, -1, 38, -1, "cell_style_6");
		setCellInfoMap_Internal("sheet20_B3", 38, -1, 38, -1, "cell_style_7");
		setCellInfoMap_Internal("sheet20_C3", 76, -1, 192, -1, "cell_style_8");
		setCellInfoMap_Internal("sheet20_D3", 268, 0, 52, 18, "cell_style_9");
		setCellInfoMap_Internal("sheet20_E3", 320, 0, 52, 18, "cell_style_9");
		setCellInfoMap_Internal("sheet20_F3", 372, 0, 38, 18, "cell_style_9");
		setCellInfoMap_Internal("sheet20_G3", 410, 0, 52, 18, "cell_style_9");
		setCellInfoMap_Internal("sheet20_H3", 462, 0, 110, 18, "cell_style_10");
		setCellInfoMap_Internal("sheet20_A4", 0, 0, 462, 19, "cell_style_11");
		setCellInfoMap_Internal("sheet20_H4", 462, 0, 110, 19, "cell_style_12");
		setCellInfoMap_Internal("sheet20_A5", 0, 0, 462, 18, "cell_style_13");
		setCellInfoMap_Internal("sheet20_H5", 462, 0, 110, 18, "cell_style_14");
	}
}
%>
