<%
/************************************************************************************
Generated by AIDesigner 5.6.0.5
************************************************************************************
보고서 제목 : 보고서 (2017/4/27 13:47:13)
작성일 : 2017년4월27일 13시47분13초
수정일 : 2017년6월14일 16시58분24초
작성자 :
************************************************************************************/
%>

<%@ page pageEncoding="UTF-8" %>
<%@ page contentType="text/html; charset=utf-8" %>

<%@ page import="java.sql.*,java.io.*,java.lang.*,java.text.*,java.util.*,java.net.URL" %>
<%@ page import="com.activeintra.manager.*" %>
<%@ page import="com.activeintra.url.*" %>
<%@ page import="com.activeintra.util.uds.*" %>
<%@ page import="org.apache.log4j.Logger" %>
<%@ page import="org.apache.log4j.PropertyConfigurator" %>


<%
Object[] userObj = null;
HttpParameterDecoder decoder = HttpParameterDecoder.newInstance(request, application);
request.setAttribute("paramsDecoder", decoder);

String reportMode = decoder.getParameter("reportMode");
String reportParams = decoder.getParameter("reportParams");
if(reportMode!=null){
	if(reportMode.equals("PDF")){
		if(reportParams == null || reportParams.toLowerCase().indexOf("pdfserversave:true") == -1){
			out.clear();
			out=pageContext.pushBody();
		}
	}
	else if(reportMode.equals("EXCEL")){
		if(reportParams == null || reportParams.toLowerCase().indexOf("excelserversave:true") == -1){
			out.clear();
			out=pageContext.pushBody();
		}
	}
	else if(reportMode.equals("AR5")){
		out.clear();
		out=pageContext.pushBody();
	}
}

ReportHandler handler = new ReportHandler(pageContext, request, response, userObj, decoder);
handler.service(out);
handler = null;
%>

<%!
private volatile ReportInitializer initializer;
//보고서 초기화 - 한번만 실행되고 사용자 Request에서 반복사용가능한 코드를 기술
public void jspInit() {
	initializer = new ReportInitializer(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
	//수정되지 않는 정적 Query변수들을 초기화
	//sql_credit_receivables
	StringBuilder sql_credit_receivables = new StringBuilder();
	sql_credit_receivables.setLength(0);
	sql_credit_receivables.append("            SELECT  AA.* ");
	sql_credit_receivables.append("            ,       CASE WHEN BB.SALE_DT IS NOT NULL ");
	sql_credit_receivables.append("                    THEN ");
	sql_credit_receivables.append("                    SUBSTR(BB.SALE_DT,0,4)||'-'|| ");
	sql_credit_receivables.append("                    SUBSTR(BB.SALE_DT,5,2)||'-'|| ");
	sql_credit_receivables.append("                    SUBSTR(BB.SALE_DT,7,2) ");
	sql_credit_receivables.append("                    ELSE '' ");
	sql_credit_receivables.append("                    END AS SALE_DT ");
	sql_credit_receivables.append("            ,       CASE WHEN CC.RCP_DT IS NOT NULL ");
	sql_credit_receivables.append("                    THEN ");
	sql_credit_receivables.append("                    SUBSTR(CC.RCP_DT ,0,4)||'-'|| ");
	sql_credit_receivables.append("                    SUBSTR(CC.RCP_DT ,5,2)||'-'|| ");
	sql_credit_receivables.append("                    SUBSTR(CC.RCP_DT ,7,2) ");
	sql_credit_receivables.append("                    ELSE '' ");
	sql_credit_receivables.append("                    END AS RCP_DT ");
	sql_credit_receivables.append(" ");
	sql_credit_receivables.append("            FROM ");
	sql_credit_receivables.append("            ( ");
	sql_credit_receivables.append("                SELECT  CCL.CORP_CODE ");
	sql_credit_receivables.append("                ,        CC.STR_CODE ");
	sql_credit_receivables.append("                ,       FN_GET_STR_NAME(CCL.STR_CODE,CCL.CORP_CODE) AS STR_NAME ");
	sql_credit_receivables.append("                ,       CC.ACCT_DEPT ");
	sql_credit_receivables.append("                ,       CC.CUST_NO ");
	sql_credit_receivables.append("                ,       CC.CUST_NAME ");
	sql_credit_receivables.append("                ,       CCL.CREDIT_SALE ");
	sql_credit_receivables.append("                ,       CCL.DPOT_AMT ");
	sql_credit_receivables.append("                ,       CCL.ACCT_REABLE ");
	sql_credit_receivables.append("                ,       FN_GET_COMMON_CODE_NM('BUSI_FLAG',CC.BUSI_FLAG,CCL.CORP_CODE) AS BUSI_FLAG_NAME ");
	sql_credit_receivables.append("                ,       FN_GET_COMMON_CODE_NM('MBR_GRADE',CC.MBR_GRADE,CCL.CORP_CODE) AS MBR_GRADE_NAME ");
	sql_credit_receivables.append("                FROM    CS_CREDIT_LEDGER    CCL ");
	sql_credit_receivables.append("                ,       CS_CUST             CC ");
	sql_credit_receivables.append("                WHERE   CCL.CORP_CODE       =   CC.CORP_CODE ");
	sql_credit_receivables.append("                AND     CCL.CUST_NO         =   CC.CUST_NO ");
	sql_credit_receivables.append("                AND     CCL.STR_CODE        =   CC.STR_CODE ");
	sql_credit_receivables.append("                AND     CCL.CORP_CODE       =   '^P_CORP_CODE^' ");
	sql_credit_receivables.append("                AND     CCL.STR_CODE        =   NVL('^P_STR_CODE^',CCL.STR_CODE) ");
	sql_credit_receivables.append("                AND     CC.BUSI_FLAG        =   NVL('^P_BUSI_FLAG^',CC.BUSI_FLAG) ");
	sql_credit_receivables.append("                AND     CC.CUST_NO          =   NVL('^P_CUST_NO^',CC.CUST_NO) ");
	sql_credit_receivables.append("                AND      FN_GET_CUST_NAME(CCL.CUST_NO,CCL.CORP_CODE) LIKE '%'|| NVL('^P_CUST_NAME^',FN_GET_CUST_NAME(CCL.CUST_NO,CCL.CORP_CODE)) ||'%' ");
	sql_credit_receivables.append("                AND     CCL.ACCT_REABLE     !=  0 ");
	sql_credit_receivables.append("            ) AA ");
	sql_credit_receivables.append("                , ");
	sql_credit_receivables.append("            ( ");
	sql_credit_receivables.append("                SELECT  * ");
	sql_credit_receivables.append("                FROM ");
	sql_credit_receivables.append("                    (SELECT SSP.CUST_NO ");
	sql_credit_receivables.append("                    ,       SSP.SALE_DT ");
	sql_credit_receivables.append("                    ,      SSP.STR_CODE ");
	sql_credit_receivables.append("                    ,      SSP.CORP_CODE ");
	sql_credit_receivables.append("                    ,      ROW_NUMBER () OVER (PARTITION BY SSP.CUST_NO ORDER BY SSP.SALE_DT DESC) ranking ");
	sql_credit_receivables.append("                    FROM    SL_SALE_PAYMENT SSP ");
	sql_credit_receivables.append("                    WHERE   SSP.CANC_FLAG IN ('0','2') ");
	sql_credit_receivables.append("                    AND     SSP.GRE_TYPE = '00' ");
	sql_credit_receivables.append("                    AND     SSP.PAY_METH = '04' ");
	sql_credit_receivables.append("                    ) A  WHERE A.ranking = 1 ");
	sql_credit_receivables.append("            ) BB ");
	sql_credit_receivables.append("                , ");
	sql_credit_receivables.append("            ( ");
	sql_credit_receivables.append("                SELECT  * ");
	sql_credit_receivables.append("                FROM ");
	sql_credit_receivables.append("                    (SELECT CLS.CUST_NO ");
	sql_credit_receivables.append("                    ,       CLS.RCP_DT ");
	sql_credit_receivables.append("                    ,       CLS.STR_CODE ");
	sql_credit_receivables.append("                    ,       CLS.CORP_CODE ");
	sql_credit_receivables.append("                    ,       ROW_NUMBER () OVER (PARTITION BY CLS.CUST_NO ORDER BY CLS.RCP_DT DESC) ranking ");
	sql_credit_receivables.append("                    FROM    CS_LEDGER_SLIP CLS ");
	sql_credit_receivables.append("                    WHERE   CLS.DPOT_FISH_YN = 'Y' ");
	sql_credit_receivables.append("                    ) A  WHERE A.ranking = 1 ");
	sql_credit_receivables.append(" ");
	sql_credit_receivables.append("            ) CC ");
	sql_credit_receivables.append("           WHERE    AA.CORP_CODE    = BB.CORP_CODE(+) ");
	sql_credit_receivables.append("           AND      AA.STR_CODE     = BB.STR_CODE(+) ");
	sql_credit_receivables.append("           AND      AA.CUST_NO      = BB.CUST_NO(+) ");
	sql_credit_receivables.append("           AND      AA.CORP_CODE    = CC.CORP_CODE(+) ");
	sql_credit_receivables.append("           AND      AA.STR_CODE     = CC.STR_CODE(+) ");
	sql_credit_receivables.append("           AND      AA.CUST_NO      = CC.CUST_NO(+) ");
	sql_credit_receivables.append("           ORDER   BY  AA.STR_CODE ");
	sql_credit_receivables.append("           ,           AA.STR_NAME ");
	sql_credit_receivables.append("           ,           AA.CUST_NAME ");
	sql_credit_receivables.append(" ");
	sql_credit_receivables.append(" ");
	initializer.prepareQuery("sql_credit_receivables", sql_credit_receivables.toString());

	//sql_time
	StringBuilder sql_time = new StringBuilder();
	sql_time.setLength(0);
	sql_time.append("SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD HH:Mi') as T ");
	sql_time.append("FROM DUAL ");
	initializer.prepareQuery("sql_time", sql_time.toString());
}

class ReportHandler{
	//공통 변수 선언
	private final Logger logger = Logger.getLogger("com.activeintra");
	private Object[] userObj = null;
	private int nStartPage;		//각 쉬트별 시작 페이지 저장
	private int nMaxPage;		//한 쉬트가 실행된 후 생성된 최대 페이지 번호 저장
	private int nPageNum;		//현재 페이지 번호
	private int nYStartPos;		//쉬트에서 Y 시작 좌표
	private int nYEndPos;		//쉬트에서 Y 끝 좌표
	private int nYCurPos;		//현재 Y 좌표
	private int nYSavePos;		//연결된 멀티 프레임 쉬트에서 시작 Y 좌표 저장
	private int nYLastPos;		//연결된 멀티 프레임 쉬트에서 각 프레임의 마지막 Y 좌표 저장
	private int nXStartPos;		//쉬트에서 X 시작 좌표
	private int nXEndPos;		//쉬트에서 X 끝 좌표
	private int nXCurPos;		//현재 X 좌표
	private int nXSavePos;		//연결된 멀티 프레임 쉬트에서 시작 X 좌표 저장
	private int  nXLastPos;		//연결된 멀티 프레임 쉬트에서 각 프레임의 마지막 X 좌표 저장
	private boolean bIsBeforePageSkip;		//조건 밴드에서 페이지 넘기기 여부 판단
	private int nLoopRef;		//절대 양식에서 루프 참조 변수
	private int CELL_OBJECT = 0;
	private int DRAW_OBJECT = 1;
	private String isEmpty="";		//빈 문자열 비교에 사용
	private Map<String, String> mapParam;

	private int nBandRepeatType;	//1이면 반복밴드 가로 반복
	private int nBandWidth;		//반복밴드의 가로 폭
	private int nBandOffset;		//반복밴드 가로 반복 offset값
	private int nYBandStart;		//반복밴드 가로 반복 Y 시작 좌표
	private int nYBandEnd;		//반복밴드 가로 반복 Y 끝 좌표
	private int nHorRepeatNum;		//반복밴드 가로 반복 횟수
	private int nHorRepeatCnt;		//반복밴드 가로 반복 횟수 카운팅
	private Map<String, Integer> mapLeft;		//셀 Left
	private Map<String, Integer> mapTop;		//셀 Top
	private Map<String, Integer> mapWidth;		//셀 Width
	private Map<String, Integer> mapHeight;		//셀 Height
	private Map<String, String> mapStyle;		//셀 Style
	private HttpServletRequest request;
	private HttpServletResponse response;
	private PageContext pageContext;
	private JspWriter out;
	private HttpParameterDecoder decoder;

	private AIScriptManager manager;
	private String reportMode="AIScript";
	private String pdfFilename="";
	private String excelFilename="";

	//-----데이터 변수 선언-----
	String AI_STRING_OBJ2 = "";
	String AI_STRING_OBJ3 = "";
	String sheet10_A1 = "";
	String sheet20_A1 = "";
	String sheet20_B1 = "";
	String sheet20_C1 = "";
	String sheet20_D1 = "";
	String sheet20_E1 = "";
	String sheet20_F1 = "";
	String sheet20_G1 = "";
	String sheet20_H1 = "";
	String sheet20_I1 = "";
	String sheet20_A2_Buf;
	int sheet20_A2_YPos;
	boolean sheet20_A2_Flag;
	String sheet20_A2 = "";
	String sheet20_B2 = "";
	String sheet20_C2 = "";
	String sheet20_D2 = "";
	String sheet20_E2 = "";
	String sheet20_F2 = "";
	String sheet20_G2 = "";
	String sheet20_H2 = "";
	double sheet20_I2 = 0;
	boolean bEnabledVirtualMerge_fv;
	String sheet20_A3 = "";
	double sheet20_I3 = 0;
	String sheet20_A4 = "";
	double sheet20_I4 = 0;

	//-----Connection, Statement, ResultSet 객체 선언-----
	private Connection conn_retail; 	 //retail Connection 객체
	private java.sql.PreparedStatement stat_credit_receivables;		//ResultSet credit_receivables 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet credit_receivables;		//ResultSet credit_receivables 객체
	private java.sql.PreparedStatement stat_time;		//ResultSet time 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet time;		//ResultSet time 객체

	//-----SQL 변수 선언-----
	private StringBuilder sql_credit_receivables = new StringBuilder();		//ResultSet credit_receivables 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_time = new StringBuilder();		//ResultSet time 객체를 생성하기 위한 쿼리문 저장

	//-----쿼리 필드 변수 선언-----
	//ResultSet credit_receivables 객체에서 필드 값을 받는 쿼리 필드 변수
	private String credit_receivables_CORP_CODE;
	private String credit_receivables_STR_CODE;
	private String credit_receivables_STR_NAME;
	private String credit_receivables_ACCT_DEPT;
	private String credit_receivables_CUST_NO;
	private String credit_receivables_CUST_NAME;
	private long credit_receivables_CREDIT_SALE;
	private long credit_receivables_DPOT_AMT;
	private long credit_receivables_ACCT_REABLE;
	private String credit_receivables_BUSI_FLAG_NAME;
	private String credit_receivables_MBR_GRADE_NAME;
	private String credit_receivables_SALE_DT;
	private String credit_receivables_RCP_DT;

	//ResultSet time 객체에서 필드 값을 받는 쿼리 필드 변수
	private String time_T;

	//파라미터 변수 선언
	String P_CORP_CODE_Param;
	String P_STR_CODE_Param;
	String P_CUST_NAME_Param;
	String P_CUST_NO_Param;
	String P_BUSI_FLAG_Param;

	//ReportHandler 생성자 함수
	ReportHandler(PageContext pageContext, HttpServletRequest request, HttpServletResponse response, Object[] userObj, HttpParameterDecoder decoder){
		this.pageContext = pageContext;
		this.request = request;
		this.response = response;
		this.userObj = userObj;
		this.decoder = decoder;
	}

	//ReportHandler 서비스 함수
	void service(JspWriter out) throws Exception{
		try{    //try 구문
			//변수 초기화
			this.out = out;
			nMaxPage = 0;   //nMaxPage 초기화

			nBandRepeatType=0;
			nBandWidth=0;
			nBandOffset=0;
			nYBandStart=0;
			nYBandEnd=0;
			nHorRepeatNum=0;
			nHorRepeatCnt=0;

			manager = new AIScriptManager(request, response, pageContext, out, logger, null);

			ServletContext context = pageContext.getServletContext();
			String temp = null;
			if(!context.getContextPath().equals("/"))
			temp = request.getRequestURI().replace(context.getContextPath(), "");
			else
			temp = request.getRequestURI();

			String path = temp.replace(".jsp", ".style");

			//셀 Rect, Style 값 저장
			setCellInfoMap();

			//파라미터 설정 함수 호출
			setParam();
			if(manager.open(reportMode, context.getRealPath(path)))
			{
				//스크립트 헤더 함수 호출
				getScriptHeader("A4", "2100x2970", "9", "VERTICAL", "14 28 14 28");

				//고정 데이터 초기화 함수 호출
				initConstVarient();

				//Connection 및 Statement 객체 생성 함수 호출
				createConnAndStateObject();

				//쿼리문 초기화 함수 호출
				initSQLConst();

				//쉬트 함수 호출
				//SHEET=Sheet1   FRAME=0 함수 호출
				executeSheet10();

				//---------------스크립트 종료---------------
				manager.scriptWrite("/AIReport", "", "", false);
				manager.close();
			}
		}catch(Throwable t){    //catch 구문
			logger.error("---service function exception raised---");
			logger.error(t.toString());
			throw (new AIException(t.toString(),t.getCause()));
		}finally{    //finally 구문
			if(manager.reportFile!=null)
			manager.reportFile.close();

			//DataSet Close
			cleanup(time, stat_time, null, null);
			cleanup(credit_receivables, stat_credit_receivables, null, null);
			cleanup(null, null, null, conn_retail);
		}    //end try
	}

	//-----쉬트 함수-----
	//-----SHEET=Sheet1   FRAME=Frame0 Start
	//-----폼 형식 : 상대 양식
	private void executeSheet10( ) throws Exception{
		//쉬트 초기화 함수 호출
		getSheetPaperInfo("A4", "2100x2970", "9", "VERTICAL", "14 0 14 28");
		initSheetVariant(27, 30, 571, 801, true);

		//시작 페이지 번호 출력
		pageWrite(nPageNum);

		//밴드 함수 호출
		getScriptFromh1(true, true);    //머리글 밴드 호출
		getScriptFromv1(true, true);    //Void 밴드 호출

		//페이지 및 좌표 설정
		nMaxPage=(int)MAX((long)nMaxPage, (long)nPageNum);    //생성된 최대 페이지 번호 구하기

		//자식 쉬트 호출
		//SHEET=Sheet2   FRAME=0 함수 호출
		executeSheet20();
	}

	//-----SHEET=Sheet2   FRAME=Frame0 Start
	//-----폼 형식 : 상대 양식
	private void executeSheet20( ) throws Exception{
		//쉬트 초기화 함수 호출
		initChildSheetVariant(27, 30, 571, 801, false, false);

		//시작 페이지 번호 출력
		pageWrite(nPageNum);

		//밴드 함수 호출
		getScriptFromv2(true, true);    //Void 밴드 호출
		getScriptFromfv(true);    //반복 밴드 호출

		//페이지 및 좌표 설정
		nMaxPage=(int)MAX((long)nMaxPage, (long)nPageNum);    //생성된 최대 페이지 번호 구하기
	}

	//-----밴드 함수-----
	//----h1 HeaderBand Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : h1
	//----밴드 종류 : 머리글 밴드
	//----bIsFrist : 쉬트 함수에서 최초로 호출될 때 true, 페이지 스킵 함수에서 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	private void getScriptFromh1(boolean bIsFirst, boolean bIsPrint) throws Exception{
		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//DataSet 객체 생성
			//ResultSet time 객체의 생성
			if(time==null){
				time = stat_time.executeQuery();
			}else{
				time.beforeFirst();
			}

			//데이터 fetch
			if(time.next()){
				setFieldVariableFromtime();	//ResultSet time에서 필드 값 설정
			}else{
				setFieldInitFromtime();	//ResultSet time의 필드 값 초기화
			}

			//데이터 변수 초기화
			AI_STRING_OBJ2="";

			//데이터 변수 할당
			AI_STRING_OBJ2 = time_T;
		}   //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 함수 호출
			writeScripth1();
		}   //end if(bIsPrint)
	}

	//----v1 VoidBand Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : v1
	//----밴드 종류 : Void 밴드
	//----bIsFrist : 부모 밴드 함수나 쉬트 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	//----nRepeatCnt : 부모 반복 밴드 수행 횟수와 연동 옵션 설정시 void 밴드가 수행할 반복 횟수 전달
	private void getScriptFromv1(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=41;    //밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//데이터 변수 할당
			sheet10_A1="외상매출미수채권";
		}    //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScriptv1();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//----v2 VoidBand Start----
	//----소속 쉬트 : SHEET=Sheet2    FRAME=Frame0
	//----밴드 이름 : v2
	//----밴드 종류 : Void 밴드
	//----bIsFrist : 부모 밴드 함수나 쉬트 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	//----nRepeatCnt : 부모 반복 밴드 수행 횟수와 연동 옵션 설정시 void 밴드가 수행할 반복 횟수 전달
	private void getScriptFromv2(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//데이터 변수 할당
			sheet20_A1="점포명";
			sheet20_B1="회원번호";
			sheet20_C1="회원명";
			sheet20_D1="회원등급";
			sheet20_E1="회원구분";
			sheet20_F1="회계코드";
			sheet20_G1="최종매출일";
			sheet20_H1="최종입금일";
			sheet20_I1="미수잔액";
		}    //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScriptv2();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//----fv_1 ConditionBand Start----
	//----소속 쉬트 : SHEET=Sheet2    FRAME=Frame0
	//----밴드 이름 : fv_1
	//----밴드 종류 : 조건 밴드
	//----bIsFrist : 부모 밴드 함수에서 최초로 호출될 때 true
	//----bIsLast : 부모 밴드 함수에서 마지막으로 호출될 때 true
	//----bIsTrue : 부모 밴드 함수에서 조건 밴드 출력 조건 플래그 값
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	private void getScriptFromfv_1(boolean bIsFirst, boolean bIsLast, boolean bIsTrue, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;	//밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//데이터 변수 초기화
			sheet20_I3=0;
		}   //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsTrue){   //조건 밴드 출력 플래그 값이 true인 경우
			//조건 밴드의 참 값
			if(bIsPrint){   //WriteBandObj() 함수 대체 코드
				if(isPageSkip(nYCurPos+nBandHeight)){
					pageSkipVirtualMergefv();
					pageSkip(10);
				}
				writeScriptfv_1();	//스크립트문 출력
				nYCurPos=nYCurPos+nBandHeight;
				sheet20_I3=0;
			}
		}else{   //조건 밴드 출력 플래그 값이 false인 경우
		}   //end if(bIsTrue)

		if(!bIsLast){   //bIsLast가 false인 경우 - 조건 밴드의 수식 계산
			//데이터 변수 할당
			sheet20_A3="소계";
			sheet20_I3=SUM(sheet20_I2, sheet20_I3);
		}   //end if(!bIsLast)
	}

	//----fv_2 ConditionBand Start----
	//----소속 쉬트 : SHEET=Sheet2    FRAME=Frame0
	//----밴드 이름 : fv_2
	//----밴드 종류 : 조건 밴드
	//----bIsFrist : 부모 밴드 함수에서 최초로 호출될 때 true
	//----bIsLast : 부모 밴드 함수에서 마지막으로 호출될 때 true
	//----bIsTrue : 부모 밴드 함수에서 조건 밴드 출력 조건 플래그 값
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	private void getScriptFromfv_2(boolean bIsFirst, boolean bIsLast, boolean bIsTrue, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;	//밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//데이터 변수 초기화
			sheet20_I4=0;
		}   //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsTrue){   //조건 밴드 출력 플래그 값이 true인 경우
			//조건 밴드의 참 값
			if(bIsPrint){   //WriteBandObj() 함수 대체 코드
				if(isPageSkip(nYCurPos+nBandHeight)){
					pageSkipVirtualMergefv();
					pageSkip(10);
				}
				writeScriptfv_2();	//스크립트문 출력
				nYCurPos=nYCurPos+nBandHeight;
				sheet20_I4=0;
			}
		}else{   //조건 밴드 출력 플래그 값이 false인 경우
		}   //end if(bIsTrue)

		if(!bIsLast){   //bIsLast가 false인 경우 - 조건 밴드의 수식 계산
			//데이터 변수 할당
			sheet20_A4="합계";
			sheet20_I4=SUM(sheet20_I2, sheet20_I4);
		}   //end if(!bIsLast)
	}

	//-----fv RepeatBand Start-----
	//-----소속 쉬트 : SHEET=Sheet2   FRAME=Frame0
	//-----밴드 이름 : fv
	//-----밴드 종류 : 반복 밴드
	//-----bIsPrint : 감추기 속성 설정 여부 true면 출력, false면 스크립트를 생성하지 않음
	private void getScriptFromfv(boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=17;    //밴드 출력 높이
		boolean bIsFirst=true;
		boolean bIsTrue_fv_1=false;   //fv_1 조건 밴드 플래그 선언
		boolean bIsTrue_fv_2=false;   //fv_2 조건 밴드 플래그 선언

		//데이터 변수 초기화
		sheet20_A2_Buf=null;
		sheet20_A2_Flag=true;
		sheet20_A2="";
		sheet20_B2="";
		sheet20_C2="";
		sheet20_D2="";
		sheet20_E2="";
		sheet20_F2="";
		sheet20_G2="";
		sheet20_H2="";
		sheet20_I2=0;
		bEnabledVirtualMerge_fv=false;

		//DataSet 객체 생성
		//ResultSet credit_receivables 객체의 생성
		if(credit_receivables==null){
			credit_receivables = stat_credit_receivables.executeQuery();
		}else{
			credit_receivables.beforeFirst();
		}

		//--while Loop Start--##
		while(credit_receivables.next()){   //자동으로 생성되는 반복 밴드의 루프문
			//데이터 fetch
			setFieldVariableFromcredit_receivables();	//RecordSet credit_receivables에서 필드 값 설정

			//조건 밴드 출력 조건문
			bIsBeforePageSkip=false;
			if(!credit_receivables_STR_NAME.equals(sheet20_A2)){    //fv_1 밴드 조건문
				bIsTrue_fv_1=true;
			}else{
				bIsTrue_fv_1=false;
			}

			if(bIsFirst){   //밴드 호출 후 루프 내에서 한번 만 실행되는 코드
				//조건 플래그 초기화
				bIsTrue_fv_1=false;    //fv_1 조건 밴드 플래그 초기화
				bIsTrue_fv_2=false;    //fv_2 조건 밴드 플래그 초기화
			}   //end if(bIsFirst)

			//데이터 변수 할당
			if(!sheet20_A2.equals(credit_receivables_STR_NAME)){
				if(!bIsFirst){
					sheet20_A2_Buf = sheet20_A2;
					sheet20_A2_Flag=true;
				}
				sheet20_A2=credit_receivables_STR_NAME;
			}
			sheet20_B2 = credit_receivables_CUST_NO;
			sheet20_C2 = credit_receivables_CUST_NAME;
			sheet20_D2 = credit_receivables_MBR_GRADE_NAME;
			sheet20_E2 = credit_receivables_BUSI_FLAG_NAME;
			sheet20_F2 = credit_receivables_ACCT_DEPT;
			sheet20_G2 = credit_receivables_SALE_DT;
			sheet20_H2 = credit_receivables_RCP_DT;
			sheet20_I2 = (double)credit_receivables_ACCT_REABLE;

			//루프 내부 가상병합 출력 함수 호출
			if(bIsPrint){
				writeScriptVirtualMergefv();
			}

			//루프 내부 조건밴드 및 스타일 함수 호출
			getScriptFromfv_1(bIsFirst, false, bIsTrue_fv_1, true);   //fv_1 조건 밴드 호출
			getScriptFromfv_2(bIsFirst, false, bIsTrue_fv_2, true);   //fv_2 조건 밴드 호출

			//AI 스크립트 출력
			if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
				if(isPageSkip(nYCurPos+nBandHeight)){   //스크립트 출력 영역 검사
					//가상병합 출력 및 한번만 데이터 Reset
					pageSkipVirtualMergefv();

					//페이지 스킵 함수 호출
					pageSkip(10);
				}   //end if(page skip test)

				//스크립트 출력 함수 호출
				writeScriptfv();

				//페이지 연결 출력 및 가상병합 플래그 Reset
				if(sheet20_A2_Flag){
					sheet20_A2_YPos=nYCurPos;
					sheet20_A2_Buf=null;
					sheet20_A2_Flag=false;
				}
				bEnabledVirtualMerge_fv=true;

				//다음 출력 좌표 설정
				nYCurPos=nYCurPos+nBandHeight;
			}   //end if(bIsPrint)

			//bIsFirst 및 출력 라인 설정
			bIsFirst=false;
		}   //while end

		if(bIsFirst){   //while 루프가 실행되지 않은 경우
		} else {   //while 루프가 실행된 경우
			//루프 외부 가상병합 출력 함수 호출
			sheet20_A2_Buf = sheet20_A2;
			if(bIsPrint){
				writeScriptVirtualMergefv();
			}

			//루프 외부 조건밴드 및 스타일 함수 호출
			getScriptFromfv_1(bIsFirst, true, true, true);   //fv_1 조건 밴드 호출
			getScriptFromfv_2(bIsFirst, true, true, true);   //fv_2 조건 밴드 호출
		}   //루프 외부 end if(bIsFirst)
	}

	//----fv 반복밴드 Page Skip시 가상 병합 데이터 설정 및 출력 함수----
	private void pageSkipVirtualMergefv(  ) throws Exception{
		//가상 병합 데이터 설정 및 출력
		if(bEnabledVirtualMerge_fv){
			if(sheet20_A2_Buf==null){
				sheet20_A2_Buf = sheet20_A2;
			}else{
				sheet20_A2_Buf=null;
			}
			sheet20_A2_Flag=true;
			writeScriptVirtualMergefv();
		}
	}

	//-----스크립트 출력 함수-----
	//----h1 스크립트 문 출력 함수----
	private void writeScripth1( ) throws Exception{
		//스크립트문 생성
		objectWrite(DRAW_OBJECT, 436, 15, 55, 14, AI_STRING_OBJ2, "AI_STRING_OBJ2", "draw_style_1");
		objectWrite(DRAW_OBJECT, 517, 15, 52, 10, AI_STRING_OBJ3, "AI_STRING_OBJ3", "draw_style_1");
	}

	//----v1 스크립트 문 출력 함수----
	private void writeScriptv1( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_A1"), nYCurPos+mapTop.get("sheet10_A1"), mapWidth.get("sheet10_A1"), mapHeight.get("sheet10_A1"), sheet10_A1, "sheet10_A1", mapStyle.get("sheet10_A1"));
		objectWrite(DRAW_OBJECT, nXCurPos+189, nYCurPos+36, 164, 0, "", "AI_HLINE_OBJ1", "draw_style_0");
	}

	//----v2 스크립트 문 출력 함수----
	private void writeScriptv2( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_A1"), nYCurPos+mapTop.get("sheet20_A1"), mapWidth.get("sheet20_A1"), mapHeight.get("sheet20_A1"), sheet20_A1, "sheet20_A1", mapStyle.get("sheet20_A1"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_B1"), nYCurPos+mapTop.get("sheet20_B1"), mapWidth.get("sheet20_B1"), mapHeight.get("sheet20_B1"), sheet20_B1, "sheet20_B1", mapStyle.get("sheet20_B1"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_C1"), nYCurPos+mapTop.get("sheet20_C1"), mapWidth.get("sheet20_C1"), mapHeight.get("sheet20_C1"), sheet20_C1, "sheet20_C1", mapStyle.get("sheet20_C1"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_D1"), nYCurPos+mapTop.get("sheet20_D1"), mapWidth.get("sheet20_D1"), mapHeight.get("sheet20_D1"), sheet20_D1, "sheet20_D1", mapStyle.get("sheet20_D1"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_E1"), nYCurPos+mapTop.get("sheet20_E1"), mapWidth.get("sheet20_E1"), mapHeight.get("sheet20_E1"), sheet20_E1, "sheet20_E1", mapStyle.get("sheet20_E1"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_F1"), nYCurPos+mapTop.get("sheet20_F1"), mapWidth.get("sheet20_F1"), mapHeight.get("sheet20_F1"), sheet20_F1, "sheet20_F1", mapStyle.get("sheet20_F1"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_G1"), nYCurPos+mapTop.get("sheet20_G1"), mapWidth.get("sheet20_G1"), mapHeight.get("sheet20_G1"), sheet20_G1, "sheet20_G1", mapStyle.get("sheet20_G1"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_H1"), nYCurPos+mapTop.get("sheet20_H1"), mapWidth.get("sheet20_H1"), mapHeight.get("sheet20_H1"), sheet20_H1, "sheet20_H1", mapStyle.get("sheet20_H1"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_I1"), nYCurPos+mapTop.get("sheet20_I1"), mapWidth.get("sheet20_I1"), mapHeight.get("sheet20_I1"), sheet20_I1, "sheet20_I1", mapStyle.get("sheet20_I1"));
	}

	//----fv_1 스크립트 문 출력 함수----
	private void writeScriptfv_1( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_A3"), nYCurPos+mapTop.get("sheet20_A3"), mapWidth.get("sheet20_A3"), mapHeight.get("sheet20_A3"), sheet20_A3, "sheet20_A3", mapStyle.get("sheet20_A3"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_I3"), nYCurPos+mapTop.get("sheet20_I3"), mapWidth.get("sheet20_I3"), mapHeight.get("sheet20_I3"), String.valueOf(sheet20_I3), "sheet20_I3", mapStyle.get("sheet20_I3"));
	}

	//----fv_2 스크립트 문 출력 함수----
	private void writeScriptfv_2( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_A4"), nYCurPos+mapTop.get("sheet20_A4"), mapWidth.get("sheet20_A4"), mapHeight.get("sheet20_A4"), sheet20_A4, "sheet20_A4", mapStyle.get("sheet20_A4"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_I4"), nYCurPos+mapTop.get("sheet20_I4"), mapWidth.get("sheet20_I4"), mapHeight.get("sheet20_I4"), String.valueOf(sheet20_I4), "sheet20_I4", mapStyle.get("sheet20_I4"));
	}

	//----fv 스크립트 문 출력 함수----
	private void writeScriptfv(  ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_B2"), nYCurPos+mapTop.get("sheet20_B2"), mapWidth.get("sheet20_B2"), mapHeight.get("sheet20_B2"), sheet20_B2, "sheet20_B2", mapStyle.get("sheet20_B2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_C2"), nYCurPos+mapTop.get("sheet20_C2"), mapWidth.get("sheet20_C2"), mapHeight.get("sheet20_C2"), sheet20_C2, "sheet20_C2", mapStyle.get("sheet20_C2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_D2"), nYCurPos+mapTop.get("sheet20_D2"), mapWidth.get("sheet20_D2"), mapHeight.get("sheet20_D2"), sheet20_D2, "sheet20_D2", mapStyle.get("sheet20_D2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_E2"), nYCurPos+mapTop.get("sheet20_E2"), mapWidth.get("sheet20_E2"), mapHeight.get("sheet20_E2"), sheet20_E2, "sheet20_E2", mapStyle.get("sheet20_E2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_F2"), nYCurPos+mapTop.get("sheet20_F2"), mapWidth.get("sheet20_F2"), mapHeight.get("sheet20_F2"), sheet20_F2, "sheet20_F2", mapStyle.get("sheet20_F2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_G2"), nYCurPos+mapTop.get("sheet20_G2"), mapWidth.get("sheet20_G2"), mapHeight.get("sheet20_G2"), sheet20_G2, "sheet20_G2", mapStyle.get("sheet20_G2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_H2"), nYCurPos+mapTop.get("sheet20_H2"), mapWidth.get("sheet20_H2"), mapHeight.get("sheet20_H2"), sheet20_H2, "sheet20_H2", mapStyle.get("sheet20_H2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_I2"), nYCurPos+mapTop.get("sheet20_I2"), mapWidth.get("sheet20_I2"), mapHeight.get("sheet20_I2"), String.valueOf(sheet20_I2), "sheet20_I2", mapStyle.get("sheet20_I2"));
	}

	//----fv VirtualMerge 스크립트 문 출력 함수----
	private void writeScriptVirtualMergefv(  ) throws Exception{
		//가상병합 스크립트문 생성
		if(sheet20_A2_Buf != null){
			objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet20_A2"), sheet20_A2_YPos, mapWidth.get("sheet20_A2"), nYCurPos-sheet20_A2_YPos, sheet20_A2_Buf, "sheet20_A2", mapStyle.get("sheet20_A2"));
		}
	}

	private void getBgImageScriptEx(int nIndex) throws Exception{
	}

	//-----Connection 및 Statement 객체 생성 함수-----
	private void createConnAndStateObject() throws Exception{
		//retail Connection 객체 생성
		Class.forName("oracle.jdbc.OracleDriver");
		conn_retail = DriverManager.getConnection("jdbc:oracle:thin:@210.219.229.37:1521:umac", "UMACSM", "dbaor!@#");
	}

	//-----ResultSet, PreparedStatement, Connection, CallableStatement Close 함수-----
	private void cleanup(Object rs, PreparedStatement st, CallableStatement cs, Connection conn){
		if(rs != null){
			try{
				if(rs instanceof ResultSet){
					((ResultSet)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.AIDataSource){
					((com.activeintra.util.uds.AIDataSource)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.XMLSetHandler){
					((com.activeintra.util.uds.XMLSetHandler)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.CSVSetHandler){
					((com.activeintra.util.uds.CSVSetHandler)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.JSONSetHandler){
					((com.activeintra.util.uds.JSONSetHandler)rs).close();
				}
			}
			catch(SQLException e){
				logger.error(e);
			}
		}

		if(st != null){
			try{
				st.close();
			}
			catch(SQLException e){
				logger.error(e);
			}
		}

		if(cs != null){
			try{
				cs.close();
			}
			catch(SQLException e){
				logger.error(e);
			}
		}

		if(conn != null){
			try{
				conn.close();
			}
			catch(SQLException e){
				logger.error(e);
			}
		}
	}

	//-----SQL문 변수 초기화 함수-----
	private void initSQLConst() throws Exception {
		stat_credit_receivables = initializer.configPreparedStatement("sql_credit_receivables", mapParam, conn_retail, null);

		stat_time = initializer.configPreparedStatement("sql_time", mapParam, conn_retail, null);
	}

	//-----ResultSet 객체에서 필드 값 설정 함수-----
	//ResultSet credit_receivables 객체에서 필드 값 설정 함수
	private void setFieldVariableFromcredit_receivables() throws Exception{
		credit_receivables_CORP_CODE = GetB(credit_receivables.getString(1));
		credit_receivables_STR_CODE = GetB(credit_receivables.getString(2));
		credit_receivables_STR_NAME = GetB(credit_receivables.getString(3));
		credit_receivables_ACCT_DEPT = GetB(credit_receivables.getString(4));
		credit_receivables_CUST_NO = GetB(credit_receivables.getString(5));
		credit_receivables_CUST_NAME = GetB(credit_receivables.getString(6));
		credit_receivables_CREDIT_SALE = credit_receivables.getLong(7);
		credit_receivables_DPOT_AMT = credit_receivables.getLong(8);
		credit_receivables_ACCT_REABLE = credit_receivables.getLong(9);
		credit_receivables_BUSI_FLAG_NAME = GetB(credit_receivables.getString(10));
		credit_receivables_MBR_GRADE_NAME = GetB(credit_receivables.getString(11));
		credit_receivables_SALE_DT = GetB(credit_receivables.getString(12));
		credit_receivables_RCP_DT = GetB(credit_receivables.getString(13));
	}

	//ResultSet credit_receivables 객체의 필드 값 초기화 함수
	private void setFieldInitFromcredit_receivables(){
		credit_receivables_CORP_CODE = "";
		credit_receivables_STR_CODE = "";
		credit_receivables_STR_NAME = "";
		credit_receivables_ACCT_DEPT = "";
		credit_receivables_CUST_NO = "";
		credit_receivables_CUST_NAME = "";
		credit_receivables_CREDIT_SALE = 0L;
		credit_receivables_DPOT_AMT = 0L;
		credit_receivables_ACCT_REABLE = 0L;
		credit_receivables_BUSI_FLAG_NAME = "";
		credit_receivables_MBR_GRADE_NAME = "";
		credit_receivables_SALE_DT = "";
		credit_receivables_RCP_DT = "";
	}

	//ResultSet time 객체에서 필드 값 설정 함수
	private void setFieldVariableFromtime() throws Exception{
		time_T = GetB(time.getString(1));
	}

	//ResultSet time 객체의 필드 값 초기화 함수
	private void setFieldInitFromtime(){
		time_T = "";
	}

	//-----고정 데이터 초기화 함수-----
	private void initConstVarientEx(){
		AI_STRING_OBJ3="Page : #PAGE/#TOTALPAGE";
	}

	//-----공통 함수 선언-----
	//파라미터 설정 함수
	private void setParam() {
		//SetParam_AutoCode
		reportMode=decoder.getParameterB("reportMode");
		if(reportMode.equals("")) {
			reportMode="HTML";
		}
		manager.setParam("pdfFilename:" + pdfFilename + "," + "excelFilename:" + excelFilename + "," + decoder.getParameterB("reportParams"));

		//char data[] = {0x14};
		//String str = new String(data);
		mapParam = new HashMap<String, String>();

		P_CORP_CODE_Param=decoder.getParameterB("P_CORP_CODE");
		//P_CORP_CODE_Param=aiReplace(P_CORP_CODE_Param, str, "\n");
		mapParam.put("P_CORP_CODE", P_CORP_CODE_Param);

		P_STR_CODE_Param=decoder.getParameterB("P_STR_CODE");
		//P_STR_CODE_Param=aiReplace(P_STR_CODE_Param, str, "\n");
		mapParam.put("P_STR_CODE", P_STR_CODE_Param);

		P_CUST_NAME_Param=decoder.getParameterB("P_CUST_NAME");
		//P_CUST_NAME_Param=aiReplace(P_CUST_NAME_Param, str, "\n");
		mapParam.put("P_CUST_NAME", P_CUST_NAME_Param);

		P_CUST_NO_Param=decoder.getParameterB("P_CUST_NO");
		//P_CUST_NO_Param=aiReplace(P_CUST_NO_Param, str, "\n");
		mapParam.put("P_CUST_NO", P_CUST_NO_Param);

		P_BUSI_FLAG_Param=decoder.getParameterB("P_BUSI_FLAG");
		//P_BUSI_FLAG_Param=aiReplace(P_BUSI_FLAG_Param, str, "\n");
		mapParam.put("P_BUSI_FLAG", P_BUSI_FLAG_Param);
	}

	//상수 데이터 초기화 래퍼 함수
	private void initConstVarient() {
		//InitConstVarient_AutoCode
		initConstVarientEx();
	}

	//배경 이미지 출력 래퍼 함수
	private void getBgImageScript(int nIndex) throws Exception{
		//GetBgImageScript_AutoCode
		getBgImageScriptEx(nIndex);
	}

	//페이지 스킵 함수
	//페이지 스킵시 호출되는 함수로서 페이지 번호를 증가시키고 페이지 지시문 출력 그리고 Y좌표 초기화
	//매개변수에 따라 해당 쉬트의 배경 이미지, 머리글 밴드, 바닥글 밴드 함수 호출
	private void pageSkip(int nIndex) throws Exception{
		//PageSkip_AutoCode
		if(nBandRepeatType==1) {
			int tmpX;
			tmpX=nXCurPos+nBandWidth+nBandOffset;
			nHorRepeatCnt=nHorRepeatCnt+1;
			if(tmpX+nBandWidth>nXEndPos || nHorRepeatCnt==nHorRepeatNum) {
				nYBandStart=nYStartPos;
				nYBandEnd=0;
				nHorRepeatCnt=0;
			}else{
				if(nYBandEnd<nYCurPos) {
					nYBandEnd=nYCurPos;
				}
				nYCurPos=nYBandStart;
				nXCurPos=tmpX;
				return;
			}
		}

		nXCurPos=nXStartPos;
		nYCurPos=nYStartPos;
		nPageNum=nPageNum+1;
		pageWrite(nPageNum);

		switch(nIndex){
			case 10:		//SHEET=Sheet=1   FRAME=0에서 페이지 스킵시
			getScriptFromh1(false, true);		//머리글 밴드 호출
			break;
		}
	}

	//페이지 스킵이 필요한지 검사하는 함수
	private boolean isPageSkip(int nTestPos){
		//IsPageSkip_AutoCode
		if(nTestPos>nYEndPos){
			return true;
		}else{
			return false;
		}
	}

	//문자의 폭을 조사하여 데이터의 출력 높이를 자동적으로 조정하는 함수
	private int getPrintHeight(String data, int[] charWidth, int fontSize, int printWidth, int printHeight, int nMaxHeight, int horMargin, int vertMargin, String styleName) throws Exception {
		//GetPrintHeight_AutoCode
		if(data.equals(isEmpty)){
			return nMaxHeight;
		}
		if(!reportMode.equals("AIScript")) {
			printWidth+=horMargin;
			printHeight+=vertMargin;
			int needHeight=(int)TextHandler.wordWrapTextEx(printWidth, data, styleName, manager.getAIStyleInfo());

			if(needHeight>printHeight) {
				needHeight=needHeight-printHeight;
			}else{
				needHeight=0;
			}

			needHeight=(int)MAX((long)needHeight,(long)nMaxHeight);
			return needHeight;
		}
		else {
			int ch;
			int len = 95;
			int []width = new int[1];
			width[0] = 0;
			int asciiWidth = 0;
			int linePitch = (int)(fontSize*1.4);
			int height = linePitch;
			int size = data.length();
			int ascIndex=0;
			printWidth = printWidth*100;

			for (int i = 0; i < size; i++) {
				ch = data.charAt(i);

				if(ch<32 && !(ch==10 || ch==20 || ch==13)){
					continue;
				}

				if((ch>64 && ch<91) || (ch>96 && ch<123)) {
					if(asciiWidth==0){
						ascIndex=i;
					}

					asciiWidth += charWidth[ch-32];
					if (i==size-1){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i+1, linePitch, printWidth, width, asciiWidth);
					}
				} else if (ch==10 || ch==20 || ch==13) {
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						asciiWidth = 0;
					}

					width[0] = 0;
					height += linePitch;

					if (ch==13) {
						if ((i != size-1) && (10 == (int)data.charAt(i+1))) {
							i++;
						}
					}
				} else {
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						asciiWidth=0;
					}

					if(ch>=32 && ch<=127){
						width[0] += charWidth[ch-32];
						if (width[0] > printWidth) {
							if (ch==32)
							{
								width[0] = 0;
							}
							else
							{
								width[0] = charWidth[ch-32];
							}
							height += linePitch;
						}
					}else{
						width[0] += charWidth[len];
						if (width[0] > printWidth) {
							width[0] = charWidth[len];
							height += linePitch;
						}
					}
				}
			}

			if (height>printHeight) {
				height=height-printHeight;
			}else{
				height=0;
			}

			height = (int)MAX((long)height,(long)nMaxHeight);
			return height;
		}
	}

	//영문 단어의 폭을 문자별로 조사하여 데이터의 출력 높이를 조정하는 함수
	private int getWordWrapHeight(String data, int[] charWidth, int nStartIndex, int nEndIndex, int linePitch, int printWidth, int []width, int asciiWidth){
		//GetWordWrapHeight_AutoCode
		int ch;
		int height=0;

		if(asciiWidth>printWidth){
			for(int i=nStartIndex; i<nEndIndex; i++){
				ch=data.charAt(i);
				width[0]+=charWidth[ch-32];
				if(width[0]>printWidth){
					width[0]=charWidth[ch-32];
					height+=linePitch;
				}
			}
		}else{
			width[0]+=asciiWidth;
			if(width[0]>printWidth){
				width[0]=asciiWidth;
				height+=linePitch;
			}
		}

		return height;
	}

	//문자의 폭을 조사하여 데이터의 출력 높이를 자동적으로 조정하고 페이지 초과시 초과하는 데이터 절삭하는 함수
	private int getPrintHeightEx(String data, String[] strSplitData, int[] charWidth, int fontSize, int printWidth, int nExtHeight, int nMaxHeight, int horMargin, int vertMargin, String styleName) throws Exception {
		//GetPrintHeightEx_AutoCode
		if(!reportMode.equals("AIScript")) {
			strSplitData[0]="";
			strSplitData[1]="";
			printWidth+=horMargin;
			nExtHeight+=vertMargin;
			int needHeight=(int)TextHandler.wordWrapTextEx(printWidth, nExtHeight, data, strSplitData, styleName, manager.getAIStyleInfo());

			if(needHeight>nExtHeight) {
				needHeight=nExtHeight;
			}

			needHeight = (int)MAX((long)needHeight,(long)nMaxHeight);
			return needHeight;
		}
		else {
			int ch;
			int i;
			int len = 95;
			int []width = new int[1];
			width[0] = 0;
			int asciiWidth = 0;
			int linePitch = (int)(fontSize*1.4);
			int height = linePitch;
			int size = data.length();
			int ascIndex=0;
			boolean bSplit=false;
			strSplitData[0]="";
			strSplitData[1]="";
			printWidth = printWidth*100;

			for (i = 0; i < size; i++) {
				ch = data.charAt(i);

				if(ch<32 && !(ch==10 || ch==20 || ch==13)){
					continue;
				}

				if ((ch>64 && ch<91) || (ch>96 && ch<123)) {
					if(asciiWidth==0){
						ascIndex=i;
					}

					asciiWidth += charWidth[ch-32];
					if (i==size-1){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i+1, linePitch, printWidth, width, asciiWidth);
						if(height>nExtHeight){
							height=nExtHeight;
							bSplit=true;
							i=ascIndex;
							break;
						}
					}
				}else if (ch==10 || ch==20 || ch==13) {
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						if(height>nExtHeight){
							height=nExtHeight;
							bSplit=true;
							i=ascIndex;
							break;
						}
						asciiWidth = 0;
					}

					width[0] = 0;
					height += linePitch;
					if (ch==13){
						if ((i != size-1) && (10 == (int)data.charAt(i+1))) {
							i++;
						}
					}

					if(height>nExtHeight){
						height=nExtHeight;
						if(i!=size-1){
							bSplit=true;
							i++;
						}
						break;
					}
				}else{
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						if(height>nExtHeight){
							height=nExtHeight;
							bSplit=true;
							i=ascIndex;
							break;
						}
						asciiWidth=0;
					}

					if(ch>=32 && ch<=127){
						width[0] += charWidth[ch-32];
						if (width[0] > printWidth) {
							if (ch==32)
							{
								width[0] = 0;
							}
							else
							{
								width[0] = charWidth[ch-32];
							}
							height += linePitch;
						}
					}else{
						width[0] += charWidth[len];
						if (width[0] > printWidth) {
							width[0] = charWidth[len];
							height += linePitch;
						}
					}

					if(height>nExtHeight){
						height=nExtHeight;
						bSplit=true;
						break;
					}
				}
			}

			if(bSplit){
				strSplitData[0]=data.substring(0, i);
				strSplitData[1]=data.substring(i);
			}

			height = (int)MAX((long)height,(long)nMaxHeight);
			return height;
		}
	}

	//스크립트 헤더 출력 함수
	private void getScriptHeader(String paper, String size, String value, String orient, String margin) throws Exception{
		//GetScriptHeader_AutoCode
		manager.scriptWrite("AIReport", "scriptVersion|docVersion|style|title", "32|12|creditReceivablesPrint.style|보고서 (2017/4/27 13:47:13)", false);
	}

	private void getSheetPaperInfo(String paper, String size, String value, String orient, String margin) throws Exception{
		//GetSheetPaperInfo_AutoCode
		manager.scriptWrite("PaperInfo", "name|size|value|orientation|margin", paper+"|"+size+"|"+value+"|"+orient+"|"+margin, true);
	}

	private void initSheetVariant(int constStartX, int constStartY, int constEndX, int constEndY, boolean bFirstFrame){
		//InitSheetVariant_AutoCode
		if(bFirstFrame){
			nStartPage=nMaxPage+1;
			nYLastPos=0;
		}
		nPageNum=nStartPage;
		nYStartPos=constStartY;
		nYEndPos=constEndY;
		nYCurPos=nYStartPos;
		nXStartPos=constStartX;
		nXEndPos=constEndX;
		CELL_OBJECT=0;
		DRAW_OBJECT=1;
		nXCurPos=nXStartPos;
	}

	private void initChildSheetVariant(int constStartX, int constStartY, int constEndX, int constEndY, boolean bIsMultiFrame, boolean bIsFirstFrame){
		//InitChildSheetVariant_AutoCode
		nXStartPos=constStartX;
		nXEndPos=constEndX;
		nXCurPos=nXStartPos;
		nYStartPos=constStartY;
		nYEndPos=constEndY;

		if(bIsMultiFrame){
			if(bIsFirstFrame){
				nStartPage=nPageNum;
				nYSavePos=nYCurPos;
				nYLastPos=0;
			}else{
				nPageNum=nStartPage;
				nYCurPos=nYSavePos;
			}
		}else{
			nStartPage=nPageNum;
		}
	}

	//Empty Row만으로 구성되어 출력 위치를 조정하기 위한 VoidBand 함수
	//nRangePos - VoidBand의 출력 영역
	//nIndex - PageSkip 함수 호출시 전달할 쉬트 인덱스
	private boolean voidBandNoneData(int nRangePos, int nIndex) throws Exception{
		//VoidBandNoneData_AutoCode
		int nTestPos;
		nTestPos=nYCurPos+nRangePos;
		if(isPageSkip(nTestPos)){
			pageSkip(nIndex);
			return true;
		}else{
			nYCurPos=nYCurPos+nRangePos;
			return false;
		}
	}

	private String Get0(String str){
		//Get0_AutoCode
		if(str==null){
			return "0";
		}else{
			if(str.equals("")){
				return "0";
			}else{
				return str;
			}
		}
	}

	private String GetB(String str){
		//GetB_AutoCode
		if(str==null){
			return "";
		}else{
			return str;
		}
	}

	private double SUM(double accVal, double tmpVal){
		//SUM(double, double)_AutoCode
		return(accVal+tmpVal);
	}

	private double SUM(double accVal, long tmpVal){
		//SUM(double, long)_AutoCode
		return(accVal+(double)tmpVal);
	}

	private long SUM(long accVal, long tmpVal){
		//SUM(long, long)_AutoCode
		return(accVal+tmpVal);
	}

	private double SUM(long accVal, double tmpVal){
		//SUM(long, double)_AutoCode
		return((double)accVal+tmpVal);
	}

	private long COUNT(long accuCNT){
		//COUNT_AutoCode
		return ++accuCNT;
	}

	private long MIN(long maxV, long maxTempV){
		//MIN(long, long)_AutoCode
		if(maxV<=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MIN(long maxV, double maxTempV){
		//MIN(long, double)_AutoCode
		if((double)maxV<=maxTempV){return (double)maxV;}
		else{return maxTempV;}
	}

	private double MIN(double maxV, double maxTempV){
		//MIN(double, double)_AutoCode
		if(maxV<=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MIN(double maxV, long maxTempV){
		//MIN(double, long)_AutoCode
		if(maxV<=maxTempV){return maxV;}
		else{return (double)maxTempV;}
	}

	private long MAX(long maxV, long maxTempV){
		//MAX(long, long)_AutoCode
		if(maxV>=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MAX(long maxV, double maxTempV){
		//MAX(long, double)_AutoCode
		if((double)maxV>=maxTempV){return (double)maxV;}
		else{return maxTempV;}
	}

	private double MAX(double maxV, double maxTempV){
		//MAX(double, double)_AutoCode
		if(maxV>=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MAX(double maxV, long maxTempV){
		//MAX(double, long)_AutoCode
		if(maxV>=maxTempV){return maxV;}
		else{return (double)maxTempV;}
	}

	private double AVG(double sumVal, long cntVal){
		//AVG(double, long)_AutoCode
		return(sumVal/cntVal);
	}

	private double AVG(long sumVal, long cntVal){
		//AVG(long, long)_AutoCode
		return((double)sumVal/(double)cntVal);
	}

	private String aiReplace(String strAll, String strSrc, String strDest) {
		//AIReplace_AutoCode
		int st = 0, ed = 0;
		final int size = strAll.length();
		ed = strAll.indexOf(strSrc);
		if (ed == -1) return strAll;

		StringBuffer buf = new StringBuffer(size);
		final int len =  strSrc.length();
		do {
			buf.append(strAll.substring(st, ed));
			buf.append(strDest);
			ed += len;
			st = ed;
		} while ((ed = strAll.indexOf(strSrc, ed)) != -1);
		if (st < size) {
			buf.append(strAll.substring(st));
		}
		return buf.toString();
	}

	private String toDate() {
		//ToDate_AutoCode
		SimpleDateFormat dateFormat=new SimpleDateFormat("'#SERVERDATE#'yyyy/MM/dd/HH/mm/ss");
		java.util.Date currentDate = new java.util.Date();
		return dateFormat.format(currentDate);
	}

	final String toKor (String en){
		//ToKor_AutoCode
		if(en==null){
			return "";
		}
		try{
			return new String(en.getBytes("ISO-8859-1"), "utf-8");
		}catch(UnsupportedEncodingException e){return en;}
	}

	private void objectWrite(int type, int left, int top, int width, int height, String data, String name, String style) throws Exception {
		//ObjectWrite_AutoCode
		manager.scriptWrite(type, left, top, width, height, data, name, style);
	}

	private void propertyWrite(int type, String name, String property, String style) throws Exception {
		//PropertyWrite_AutoCode
		manager.scriptWrite(type, name, property, style);
	}

	private void pageWrite(int pageNum) throws Exception {
		//PageWrite_AutoCode
		manager.scriptWrite("Page", "number", Integer.toString(pageNum), true);
	}

	private void objectCellWrite(String name, String data, int nMoveX, int nMoveY) throws Exception {
		objectWrite(CELL_OBJECT, nMoveX+(nXCurPos+mapLeft.get(name)), nMoveY+(nYCurPos+mapTop.get(name)), mapWidth.get(name), mapHeight.get(name), data, name, mapStyle.get(name));
	}

	public String checkParam(String param) {
		param = param.replace("'", "");
		param = param.replace(";", "");
		param = param.replace("|", "");
		param = param.replace(":", "");
		param = param.replace("+", "");
		param = param.replace("\"", "");
		param = param.replace("\\", "");
		param = param.replace("--", "");
		param = param.replace("/", "");
		param = param.replaceAll("(?i)select", "");
		param = param.replaceAll("(?i)union", "");
		param = param.replaceAll("(?i)delete", "");
		param = param.replaceAll("(?i)update", "");
		param = param.replaceAll("(?i)insert", "");
		param = param.replaceAll("(?i)create", "");
		param = param.replaceAll("(?i)alter", "");
		param = param.replaceAll("(?i)drop", "");
		param = param.replaceAll("(?i)grant", "");
		param = param.replaceAll("(?i)revoke", "");
		param = param.replaceAll("(?i)merge", "");
		return param;
	}

	public String checkAITag(String strText) {
		strText = strText.replace("AI{P}", "^");
		strText = strText.replace("AI{F}", "@");
		strText = strText.replace("AI{S}", "#");
		strText = strText.replace("AI{E}", "=");
		return strText;
	}

	//셀 Rect, Style값 Map 저장
	public void setCellInfoMap_Internal(String name, int left, int top, int width, int height, String style) throws Exception {
		if( left != -1 ) {
			mapLeft.put(name, left);
		}
		if( top != -1 ) {
			mapTop.put(name, top);
		}
		if( width != -1 ) {
			mapWidth.put(name, width);
		}
		if( height != -1 ) {
			mapHeight.put(name, height);
		}
		if( style != null && !style.equals("") ) {
			mapStyle.put(name, style);
		}
	}

	//셀 Rect, Style값 저장
	public void setCellInfoMap() throws Exception {
		mapLeft = new HashMap<String, Integer>();
		mapTop = new HashMap<String, Integer>();
		mapWidth = new HashMap<String, Integer>();
		mapHeight = new HashMap<String, Integer>();
		mapStyle = new HashMap<String, String>();
		setCellInfoMap_Internal("sheet10_A1", 0, 0, 544, 41, "cell_style_0");
		setCellInfoMap_Internal("sheet20_A1", 0, 0, 55, 20, "cell_style_1");
		setCellInfoMap_Internal("sheet20_B1", 55, 0, 40, 20, "cell_style_1");
		setCellInfoMap_Internal("sheet20_C1", 95, 0, 119, 20, "cell_style_1");
		setCellInfoMap_Internal("sheet20_D1", 214, 0, 60, 20, "cell_style_1");
		setCellInfoMap_Internal("sheet20_E1", 274, 0, 53, 20, "cell_style_1");
		setCellInfoMap_Internal("sheet20_F1", 327, 0, 39, 20, "cell_style_1");
		setCellInfoMap_Internal("sheet20_G1", 366, 0, 51, 20, "cell_style_1");
		setCellInfoMap_Internal("sheet20_H1", 417, 0, 51, 20, "cell_style_1");
		setCellInfoMap_Internal("sheet20_I1", 468, 0, 76, 20, "cell_style_1");
		setCellInfoMap_Internal("sheet20_A2", 0, -1, 55, -1, "cell_style_2");
		setCellInfoMap_Internal("sheet20_B2", 55, 0, 40, 17, "cell_style_3");
		setCellInfoMap_Internal("sheet20_C2", 95, 0, 119, 17, "cell_style_4");
		setCellInfoMap_Internal("sheet20_D2", 214, 0, 60, 17, "cell_style_3");
		setCellInfoMap_Internal("sheet20_E2", 274, 0, 53, 17, "cell_style_5");
		setCellInfoMap_Internal("sheet20_F2", 327, 0, 39, 17, "cell_style_3");
		setCellInfoMap_Internal("sheet20_G2", 366, 0, 51, 17, "cell_style_3");
		setCellInfoMap_Internal("sheet20_H2", 417, 0, 51, 17, "cell_style_3");
		setCellInfoMap_Internal("sheet20_I2", 468, 0, 76, 17, "cell_style_6");
		setCellInfoMap_Internal("sheet20_A3", 0, 0, 468, 20, "cell_style_7");
		setCellInfoMap_Internal("sheet20_I3", 468, 0, 76, 20, "cell_style_8");
		setCellInfoMap_Internal("sheet20_A4", 0, 0, 468, 20, "cell_style_9");
		setCellInfoMap_Internal("sheet20_I4", 468, 0, 76, 20, "cell_style_10");
	}
}
%>
